source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
xcodeproj 'Vaavud'
link_with 'Vaavud'
pod 'Mixpanel'
pod 'Dropbox-iOS-SDK'
pod 'Amplitude-iOS', '~> 3.2.1'
pod 'Firebase'
pod 'GeoFire', '>= 1.1'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'