source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
xcodeproj 'Vaavud'
link_with 'Vaavud'
pod 'Dropbox-iOS-SDK'
pod 'Amplitude-iOS'
pod 'Firebase', '~> 2.4.2'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'GeoFire'