source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
xcodeproj 'Vaavud'
link_with 'Vaavud'
pod 'Dropbox-iOS-SDK'
pod 'Amplitude-iOS', '~> 3.4.1'
pod 'Mixpanel'
pod 'Firebase', '>= 2.4.2'
pod 'GeoFire', '>= 1.1'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'