//
//  VaavudStyle.swift
//  Vaavud
//
//  Created by Grustaf on 02/02/15.
//  Copyright (c) 2015 Vaavud. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class VaavudStyle : NSObject {

    //// Cache

    private struct Cache {
        static var vaavudRed: UIColor = UIColor(red: 0.820, green: 0.165, blue: 0.184, alpha: 1.000)
        static var vaavudBlue: UIColor = UIColor(red: 0.000, green: 0.631, blue: 0.882, alpha: 1.000)
        static var vaavudDarkGrey: UIColor = UIColor(red: 0.188, green: 0.243, blue: 0.282, alpha: 1.000)
        static var vaavudLightGrey: UIColor = UIColor(red: 0.478, green: 0.525, blue: 0.549, alpha: 1.000)
        static var vaavudClear: UIColor = VaavudStyle.vaavudLightGrey.colorWithAlpha(0)
        static var gradient: CGGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [VaavudStyle.vaavudClear.CGColor, VaavudStyle.vaavudLightGrey.CGColor], [0, 1])
        static var image: UIImage?

    }

    //// Colors

    public class var vaavudRed: UIColor { return Cache.vaavudRed }
    public class var vaavudBlue: UIColor { return Cache.vaavudBlue }
    public class var vaavudDarkGrey: UIColor { return Cache.vaavudDarkGrey }
    public class var vaavudLightGrey: UIColor { return Cache.vaavudLightGrey }
    public class var vaavudClear: UIColor { return Cache.vaavudClear }

    //// Gradients

    public class var gradient: CGGradient { return Cache.gradient }

    //// Images

    public class var image: UIImage {
        if Cache.image == nil {
            Cache.image = UIImage(named: "image")!
        }
        return Cache.image!
    }

    //// Drawing Methods

    public class func drawVaavudTemperature(#height: CGFloat, reading: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let scale: CGFloat = height / 100.0
        let tempGaugeYOffset: CGFloat = 61 - 0.5 * reading * 100

        //// Bezier 2 Drawing
        CGContextSaveGState(context)
        CGContextScaleCTM(context, scale, scale)

        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(29.97, 64.86))
        bezier2Path.addLineToPoint(CGPointMake(29.97, 13.08))
        bezier2Path.addCurveToPoint(CGPointMake(21.9, 5.45), controlPoint1: CGPointMake(29.97, 8.84), controlPoint2: CGPointMake(26.34, 5.45))
        bezier2Path.addCurveToPoint(CGPointMake(13.83, 13.08), controlPoint1: CGPointMake(17.42, 5.45), controlPoint2: CGPointMake(13.83, 8.88))
        bezier2Path.addLineToPoint(CGPointMake(13.83, 64.67))
        bezier2Path.addCurveToPoint(CGPointMake(12.63, 66.89), controlPoint1: CGPointMake(13.83, 65.55), controlPoint2: CGPointMake(13.39, 66.37))
        bezier2Path.addCurveToPoint(CGPointMake(5.76, 79.39), controlPoint1: CGPointMake(8.34, 69.81), controlPoint2: CGPointMake(5.76, 74.35))
        bezier2Path.addCurveToPoint(CGPointMake(21.9, 94.65), controlPoint1: CGPointMake(5.76, 87.88), controlPoint2: CGPointMake(12.93, 94.65))
        bezier2Path.addCurveToPoint(CGPointMake(38.04, 79.39), controlPoint1: CGPointMake(30.87, 94.65), controlPoint2: CGPointMake(38.04, 87.88))
        bezier2Path.addCurveToPoint(CGPointMake(31.17, 67.07), controlPoint1: CGPointMake(38.04, 74.51), controlPoint2: CGPointMake(35.44, 69.98))
        bezier2Path.addCurveToPoint(CGPointMake(29.97, 64.86), controlPoint1: CGPointMake(30.41, 66.56), controlPoint2: CGPointMake(29.97, 65.73))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(35.73, 64.86))
        bezier2Path.addLineToPoint(CGPointMake(34.53, 62.64))
        bezier2Path.addCurveToPoint(CGPointMake(43.8, 79.39), controlPoint1: CGPointMake(40.27, 66.55), controlPoint2: CGPointMake(43.8, 72.71))
        bezier2Path.addCurveToPoint(CGPointMake(21.9, 100.1), controlPoint1: CGPointMake(43.8, 90.89), controlPoint2: CGPointMake(34.06, 100.1))
        bezier2Path.addCurveToPoint(CGPointMake(0, 79.39), controlPoint1: CGPointMake(9.74, 100.1), controlPoint2: CGPointMake(0, 90.89))
        bezier2Path.addCurveToPoint(CGPointMake(9.27, 62.46), controlPoint1: CGPointMake(0, 72.56), controlPoint2: CGPointMake(3.5, 66.39))
        bezier2Path.addLineToPoint(CGPointMake(8.07, 64.67))
        bezier2Path.addLineToPoint(CGPointMake(8.07, 13.08))
        bezier2Path.addCurveToPoint(CGPointMake(21.9, -0), controlPoint1: CGPointMake(8.07, 5.89), controlPoint2: CGPointMake(14.22, -0))
        bezier2Path.addCurveToPoint(CGPointMake(35.73, 13.08), controlPoint1: CGPointMake(29.51, -0), controlPoint2: CGPointMake(35.73, 5.82))
        bezier2Path.addLineToPoint(CGPointMake(35.73, 64.86))
        bezier2Path.closePath()
        VaavudStyle.vaavudDarkGrey.setFill()
        bezier2Path.fill()

        CGContextRestoreGState(context)


        //// Bezier Drawing
        CGContextSaveGState(context)
        CGContextScaleCTM(context, scale, scale)

        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(26.13, (tempGaugeYOffset - 0.002)))
        bezierPath.addCurveToPoint(CGPointMake(26.13, 68.13), controlPoint1: CGPointMake(26.13, (tempGaugeYOffset - 0.002) - 0), controlPoint2: CGPointMake(26.13, 62.98))
        bezierPath.addLineToPoint(CGPointMake(29.01, 69.94))
        bezierPath.addCurveToPoint(CGPointMake(34, 79.39), controlPoint1: CGPointMake(32.27, 72.12), controlPoint2: CGPointMake(34.19, 75.76))
        bezierPath.addCurveToPoint(CGPointMake(21.71, 91.02), controlPoint1: CGPointMake(34, 85.75), controlPoint2: CGPointMake(28.43, 91.02))
        bezierPath.addCurveToPoint(CGPointMake(9.41, 79.39), controlPoint1: CGPointMake(14.98, 91.02), controlPoint2: CGPointMake(9.41, 85.75))
        bezierPath.addCurveToPoint(CGPointMake(14.6, 69.94), controlPoint1: CGPointMake(9.41, 75.76), controlPoint2: CGPointMake(11.33, 72.12))
        bezierPath.addLineToPoint(CGPointMake(17.48, 68.13))
        bezierPath.addCurveToPoint(CGPointMake(17.48, (tempGaugeYOffset + 0.001)), controlPoint1: CGPointMake(17.48, 62.98), controlPoint2: CGPointMake(17.48, (tempGaugeYOffset + 0.001)))
        bezierPath.addLineToPoint(CGPointMake(26.13, (tempGaugeYOffset + 0.001)))
        bezierPath.addLineToPoint(CGPointMake(26.13, (tempGaugeYOffset - 0.002)))
        bezierPath.closePath()
        VaavudStyle.vaavudDarkGrey.setFill()
        bezierPath.fill()

        CGContextRestoreGState(context)
    }

    public class func drawVaavudPressure(#height: CGFloat, reading: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let scale: CGFloat = height / 100.0
        let pressureGaugeCenterX: CGFloat = 50 * scale
        let pressureGaugeCenterY: CGFloat = 50 * scale
        let pressureGaugeRotation: CGFloat = -175 - 280 * reading

        //// Oval 4 Drawing
        CGContextSaveGState(context)
        CGContextScaleCTM(context, scale, scale)

        var oval4Path = UIBezierPath(ovalInRect: CGRectMake(36.1, 36.1, 28.2, 28.2))
        VaavudStyle.vaavudDarkGrey.setFill()
        oval4Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, pressureGaugeCenterX, pressureGaugeCenterY)
        CGContextRotateCTM(context, -pressureGaugeRotation * CGFloat(M_PI) / 180)
        CGContextScaleCTM(context, scale, scale)

        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(27.86, -27.75))
        bezier2Path.addLineToPoint(CGPointMake(-21.72, 11.81))
        bezier2Path.addLineToPoint(CGPointMake(-11.5, 22.03))
        bezier2Path.addLineToPoint(CGPointMake(27.86, -27.75))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        VaavudStyle.vaavudDarkGrey.setFill()
        bezier2Path.fill()

        CGContextRestoreGState(context)


        //// Oval 3 Drawing
        CGContextSaveGState(context)
        CGContextScaleCTM(context, scale, scale)

        var oval3Path = UIBezierPath()
        oval3Path.moveToPoint(CGPointMake(94.58, 50))
        oval3Path.addCurveToPoint(CGPointMake(50, 5.42), controlPoint1: CGPointMake(94.58, 25.38), controlPoint2: CGPointMake(74.62, 5.42))
        oval3Path.addCurveToPoint(CGPointMake(5.42, 50), controlPoint1: CGPointMake(25.38, 5.42), controlPoint2: CGPointMake(5.42, 25.38))
        oval3Path.addCurveToPoint(CGPointMake(50, 94.58), controlPoint1: CGPointMake(5.42, 74.62), controlPoint2: CGPointMake(25.38, 94.58))
        oval3Path.addCurveToPoint(CGPointMake(94.58, 50), controlPoint1: CGPointMake(74.62, 94.58), controlPoint2: CGPointMake(94.58, 74.62))
        oval3Path.closePath()
        oval3Path.moveToPoint(CGPointMake(100, 50))
        oval3Path.addCurveToPoint(CGPointMake(50, 100), controlPoint1: CGPointMake(100, 77.61), controlPoint2: CGPointMake(77.61, 100))
        oval3Path.addCurveToPoint(CGPointMake(0, 50), controlPoint1: CGPointMake(22.39, 100), controlPoint2: CGPointMake(-0, 77.61))
        oval3Path.addCurveToPoint(CGPointMake(50, 0), controlPoint1: CGPointMake(0, 22.39), controlPoint2: CGPointMake(22.39, 0))
        oval3Path.addCurveToPoint(CGPointMake(100, 50), controlPoint1: CGPointMake(77.61, 0), controlPoint2: CGPointMake(100, 22.39))
        oval3Path.closePath()
        VaavudStyle.vaavudDarkGrey.setFill()
        oval3Path.fill()

        CGContextRestoreGState(context)
    }

    public class func drawVaavudGustiness(#height: CGFloat, reading: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let scale: CGFloat = height / 100.0
        let pos = CGPointMake(scale * 5 * sin(180 * reading * CGFloat(M_PI)/180) * sin(reading * 300 * CGFloat(M_PI)/180), scale * 10 * sin(180 * reading * CGFloat(M_PI)/180) * sin((reading * 500 + 3) * CGFloat(M_PI)/180))

        //// Bezier 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, pos.x, pos.y)
        CGContextScaleCTM(context, scale, scale)

        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(10.27, 81.5))
        bezier2Path.addCurveToPoint(CGPointMake(37.14, 14.4), controlPoint1: CGPointMake(-0.81, 55.67), controlPoint2: CGPointMake(11.11, 25.64))
        bezier2Path.addCurveToPoint(CGPointMake(90.86, 36.04), controlPoint1: CGPointMake(57.96, 5.68), controlPoint2: CGPointMake(81.96, 15.24))
        bezier2Path.addCurveToPoint(CGPointMake(73.74, 78.98), controlPoint1: CGPointMake(97.91, 52.65), controlPoint2: CGPointMake(90.36, 71.77))
        bezier2Path.addCurveToPoint(CGPointMake(39.32, 65.23), controlPoint1: CGPointMake(60.47, 84.69), controlPoint2: CGPointMake(45.03, 78.48))
        bezier2Path.addCurveToPoint(CGPointMake(50.4, 37.72), controlPoint1: CGPointMake(34.79, 54.49), controlPoint2: CGPointMake(39.65, 42.25))
        bezier2Path.addCurveToPoint(CGPointMake(72.39, 46.44), controlPoint1: CGPointMake(58.96, 34.03), controlPoint2: CGPointMake(68.7, 38.05))
        bezier2Path.addCurveToPoint(CGPointMake(65.34, 64.05), controlPoint1: CGPointMake(75.25, 53.15), controlPoint2: CGPointMake(72.23, 61.04))
        bezier2Path.addCurveToPoint(CGPointMake(51.24, 58.35), controlPoint1: CGPointMake(59.97, 66.4), controlPoint2: CGPointMake(53.59, 63.89))
        bezier2Path.addCurveToPoint(CGPointMake(55.77, 47.11), controlPoint1: CGPointMake(49.39, 53.99), controlPoint2: CGPointMake(51.41, 48.96))
        bezier2Path.addCurveToPoint(CGPointMake(64.84, 50.63), controlPoint1: CGPointMake(59.3, 45.6), controlPoint2: CGPointMake(63.33, 47.28))
        bezier2Path.lineCapStyle = kCGLineCapRound;

        bezier2Path.lineJoinStyle = kCGLineJoinRound;

        VaavudStyle.vaavudDarkGrey.setStroke()
        bezier2Path.lineWidth = 5
        bezier2Path.stroke()

        CGContextRestoreGState(context)
    }

    public class func drawVaavudWindchill(#height: CGFloat, reading: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let scale: CGFloat = height / 100.0
        let centerX: CGFloat = 50 * scale
        let centerY: CGFloat = 50 * scale
        let windchillRotation: CGFloat = -reading * 360

        //// Bezier Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, centerX, centerY)
        CGContextRotateCTM(context, -windchillRotation * CGFloat(M_PI) / 180)
        CGContextScaleCTM(context, scale, scale)

        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(-47.29, -2.71))
        bezierPath.addLineToPoint(CGPointMake(47.29, -2.71))
        bezierPath.addCurveToPoint(CGPointMake(50, 0), controlPoint1: CGPointMake(48.79, -2.71), controlPoint2: CGPointMake(50, -1.5))
        bezierPath.addCurveToPoint(CGPointMake(47.29, 2.71), controlPoint1: CGPointMake(50, 1.5), controlPoint2: CGPointMake(48.79, 2.71))
        bezierPath.addLineToPoint(CGPointMake(-47.29, 2.71))
        bezierPath.addCurveToPoint(CGPointMake(-50, 0), controlPoint1: CGPointMake(-48.79, 2.71), controlPoint2: CGPointMake(-50, 1.5))
        bezierPath.addCurveToPoint(CGPointMake(-47.29, -2.71), controlPoint1: CGPointMake(-50, -1.5), controlPoint2: CGPointMake(-48.79, -2.71))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(26.59, -1.9))
        bezierPath.addLineToPoint(CGPointMake(36.34, -11.82))
        bezierPath.addCurveToPoint(CGPointMake(40.16, -11.86), controlPoint1: CGPointMake(37.38, -12.89), controlPoint2: CGPointMake(39.1, -12.91))
        bezierPath.addCurveToPoint(CGPointMake(40.2, -8.03), controlPoint1: CGPointMake(41.23, -10.81), controlPoint2: CGPointMake(41.25, -9.1))
        bezierPath.addLineToPoint(CGPointMake(30.45, 1.9))
        bezierPath.addCurveToPoint(CGPointMake(26.62, 1.93), controlPoint1: CGPointMake(29.4, 2.96), controlPoint2: CGPointMake(27.69, 2.98))
        bezierPath.addCurveToPoint(CGPointMake(26.59, -1.9), controlPoint1: CGPointMake(25.56, 0.88), controlPoint2: CGPointMake(25.54, -0.83))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(30.43, -1.91))
        bezierPath.addLineToPoint(CGPointMake(40.18, 7.83))
        bezierPath.addCurveToPoint(CGPointMake(40.18, 11.66), controlPoint1: CGPointMake(41.24, 8.89), controlPoint2: CGPointMake(41.24, 10.6))
        bezierPath.addCurveToPoint(CGPointMake(36.35, 11.66), controlPoint1: CGPointMake(39.12, 12.72), controlPoint2: CGPointMake(37.41, 12.72))
        bezierPath.addLineToPoint(CGPointMake(26.61, 1.91))
        bezierPath.addCurveToPoint(CGPointMake(26.61, -1.91), controlPoint1: CGPointMake(25.55, 0.86), controlPoint2: CGPointMake(25.55, -0.86))
        bezierPath.addCurveToPoint(CGPointMake(30.43, -1.91), controlPoint1: CGPointMake(27.66, -2.97), controlPoint2: CGPointMake(29.38, -2.97))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-30.43, 1.91))
        bezierPath.addLineToPoint(CGPointMake(-40.36, -8.01))
        bezierPath.addCurveToPoint(CGPointMake(-40.36, -11.84), controlPoint1: CGPointMake(-41.42, -9.07), controlPoint2: CGPointMake(-41.42, -10.78))
        bezierPath.addCurveToPoint(CGPointMake(-36.53, -11.84), controlPoint1: CGPointMake(-39.3, -12.9), controlPoint2: CGPointMake(-37.59, -12.9))
        bezierPath.addLineToPoint(CGPointMake(-26.61, -1.91))
        bezierPath.addCurveToPoint(CGPointMake(-26.61, 1.91), controlPoint1: CGPointMake(-25.55, -0.86), controlPoint2: CGPointMake(-25.55, 0.86))
        bezierPath.addCurveToPoint(CGPointMake(-30.43, 1.91), controlPoint1: CGPointMake(-27.66, 2.97), controlPoint2: CGPointMake(-29.38, 2.97))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-26.62, 1.93))
        bezierPath.addLineToPoint(CGPointMake(-36.55, 11.68))
        bezierPath.addCurveToPoint(CGPointMake(-40.38, 11.64), controlPoint1: CGPointMake(-37.62, 12.73), controlPoint2: CGPointMake(-39.33, 12.71))
        bezierPath.addCurveToPoint(CGPointMake(-40.34, 7.82), controlPoint1: CGPointMake(-41.43, 10.58), controlPoint2: CGPointMake(-41.41, 8.86))
        bezierPath.addLineToPoint(CGPointMake(-30.42, -1.93))
        bezierPath.addCurveToPoint(CGPointMake(-26.59, -1.9), controlPoint1: CGPointMake(-29.35, -2.98), controlPoint2: CGPointMake(-27.64, -2.96))
        bezierPath.addCurveToPoint(CGPointMake(-26.62, 1.93), controlPoint1: CGPointMake(-25.54, -0.83), controlPoint2: CGPointMake(-25.56, 0.88))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(2.71, -47.29))
        bezierPath.addLineToPoint(CGPointMake(2.71, 47.29))
        bezierPath.addCurveToPoint(CGPointMake(0, 50), controlPoint1: CGPointMake(2.71, 48.79), controlPoint2: CGPointMake(1.5, 50))
        bezierPath.addCurveToPoint(CGPointMake(-2.71, 47.29), controlPoint1: CGPointMake(-1.5, 50), controlPoint2: CGPointMake(-2.71, 48.79))
        bezierPath.addLineToPoint(CGPointMake(-2.71, -47.29))
        bezierPath.addCurveToPoint(CGPointMake(0, -50), controlPoint1: CGPointMake(-2.71, -48.79), controlPoint2: CGPointMake(-1.5, -50))
        bezierPath.addCurveToPoint(CGPointMake(2.71, -47.29), controlPoint1: CGPointMake(1.5, -50), controlPoint2: CGPointMake(2.71, -48.79))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(1.91, 26.61))
        bezierPath.addLineToPoint(CGPointMake(11.66, 36.35))
        bezierPath.addCurveToPoint(CGPointMake(11.66, 40.18), controlPoint1: CGPointMake(12.72, 37.41), controlPoint2: CGPointMake(12.72, 39.12))
        bezierPath.addCurveToPoint(CGPointMake(7.83, 40.18), controlPoint1: CGPointMake(10.6, 41.24), controlPoint2: CGPointMake(8.89, 41.24))
        bezierPath.addLineToPoint(CGPointMake(-1.91, 30.43))
        bezierPath.addCurveToPoint(CGPointMake(-1.91, 26.61), controlPoint1: CGPointMake(-2.97, 29.38), controlPoint2: CGPointMake(-2.97, 27.66))
        bezierPath.addCurveToPoint(CGPointMake(1.91, 26.61), controlPoint1: CGPointMake(-0.86, 25.55), controlPoint2: CGPointMake(0.86, 25.55))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(1.9, 30.45))
        bezierPath.addLineToPoint(CGPointMake(-8.03, 40.2))
        bezierPath.addCurveToPoint(CGPointMake(-11.86, 40.16), controlPoint1: CGPointMake(-9.1, 41.25), controlPoint2: CGPointMake(-10.81, 41.23))
        bezierPath.addCurveToPoint(CGPointMake(-11.82, 36.34), controlPoint1: CGPointMake(-12.91, 39.1), controlPoint2: CGPointMake(-12.89, 37.38))
        bezierPath.addLineToPoint(CGPointMake(-1.9, 26.59))
        bezierPath.addCurveToPoint(CGPointMake(1.93, 26.62), controlPoint1: CGPointMake(-0.83, 25.54), controlPoint2: CGPointMake(0.88, 25.56))
        bezierPath.addCurveToPoint(CGPointMake(1.9, 30.45), controlPoint1: CGPointMake(2.98, 27.69), controlPoint2: CGPointMake(2.96, 29.4))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-1.93, -30.42))
        bezierPath.addLineToPoint(CGPointMake(7.82, -40.34))
        bezierPath.addCurveToPoint(CGPointMake(11.64, -40.38), controlPoint1: CGPointMake(8.86, -41.41), controlPoint2: CGPointMake(10.58, -41.43))
        bezierPath.addCurveToPoint(CGPointMake(11.68, -36.55), controlPoint1: CGPointMake(12.71, -39.33), controlPoint2: CGPointMake(12.73, -37.62))
        bezierPath.addLineToPoint(CGPointMake(1.93, -26.62))
        bezierPath.addCurveToPoint(CGPointMake(-1.9, -26.59), controlPoint1: CGPointMake(0.88, -25.56), controlPoint2: CGPointMake(-0.83, -25.54))
        bezierPath.addCurveToPoint(CGPointMake(-1.93, -30.42), controlPoint1: CGPointMake(-2.96, -27.64), controlPoint2: CGPointMake(-2.98, -29.35))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-1.91, -26.61))
        bezierPath.addLineToPoint(CGPointMake(-11.84, -36.53))
        bezierPath.addCurveToPoint(CGPointMake(-11.84, -40.36), controlPoint1: CGPointMake(-12.9, -37.59), controlPoint2: CGPointMake(-12.9, -39.3))
        bezierPath.addCurveToPoint(CGPointMake(-8.01, -40.36), controlPoint1: CGPointMake(-10.78, -41.42), controlPoint2: CGPointMake(-9.07, -41.42))
        bezierPath.addLineToPoint(CGPointMake(1.91, -30.43))
        bezierPath.addCurveToPoint(CGPointMake(1.91, -26.61), controlPoint1: CGPointMake(2.97, -29.38), controlPoint2: CGPointMake(2.97, -27.66))
        bezierPath.addCurveToPoint(CGPointMake(-1.91, -26.61), controlPoint1: CGPointMake(0.86, -25.55), controlPoint2: CGPointMake(-0.86, -25.55))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-31.48, -35.31))
        bezierPath.addLineToPoint(CGPointMake(35.31, 31.48))
        bezierPath.addCurveToPoint(CGPointMake(35.31, 35.31), controlPoint1: CGPointMake(36.37, 32.54), controlPoint2: CGPointMake(36.37, 34.25))
        bezierPath.addCurveToPoint(CGPointMake(31.48, 35.31), controlPoint1: CGPointMake(34.25, 36.37), controlPoint2: CGPointMake(32.54, 36.37))
        bezierPath.addLineToPoint(CGPointMake(-35.31, -31.48))
        bezierPath.addCurveToPoint(CGPointMake(-35.31, -35.31), controlPoint1: CGPointMake(-36.37, -32.54), controlPoint2: CGPointMake(-36.37, -34.25))
        bezierPath.addCurveToPoint(CGPointMake(-31.48, -35.31), controlPoint1: CGPointMake(-34.25, -36.37), controlPoint2: CGPointMake(-32.54, -36.37))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(20.04, 17.33))
        bezierPath.addLineToPoint(CGPointMake(33.94, 17.33))
        bezierPath.addCurveToPoint(CGPointMake(36.64, 20.04), controlPoint1: CGPointMake(35.43, 17.33), controlPoint2: CGPointMake(36.64, 18.54))
        bezierPath.addCurveToPoint(CGPointMake(33.94, 22.74), controlPoint1: CGPointMake(36.64, 21.53), controlPoint2: CGPointMake(35.43, 22.74))
        bezierPath.addLineToPoint(CGPointMake(20.04, 22.74))
        bezierPath.addCurveToPoint(CGPointMake(17.33, 20.04), controlPoint1: CGPointMake(18.54, 22.74), controlPoint2: CGPointMake(17.33, 21.53))
        bezierPath.addCurveToPoint(CGPointMake(20.04, 17.33), controlPoint1: CGPointMake(17.33, 18.54), controlPoint2: CGPointMake(18.54, 17.33))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(22.74, 20.04))
        bezierPath.addLineToPoint(CGPointMake(22.74, 33.94))
        bezierPath.addCurveToPoint(CGPointMake(20.04, 36.64), controlPoint1: CGPointMake(22.74, 35.43), controlPoint2: CGPointMake(21.53, 36.64))
        bezierPath.addCurveToPoint(CGPointMake(17.33, 33.94), controlPoint1: CGPointMake(18.54, 36.64), controlPoint2: CGPointMake(17.33, 35.43))
        bezierPath.addLineToPoint(CGPointMake(17.33, 20.04))
        bezierPath.addCurveToPoint(CGPointMake(20.04, 17.33), controlPoint1: CGPointMake(17.33, 18.54), controlPoint2: CGPointMake(18.54, 17.33))
        bezierPath.addCurveToPoint(CGPointMake(22.74, 20.04), controlPoint1: CGPointMake(21.53, 17.33), controlPoint2: CGPointMake(22.74, 18.54))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-22.92, -20.22))
        bezierPath.addLineToPoint(CGPointMake(-22.92, -34.12))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, -36.82), controlPoint1: CGPointMake(-22.92, -35.61), controlPoint2: CGPointMake(-21.71, -36.82))
        bezierPath.addCurveToPoint(CGPointMake(-17.51, -34.12), controlPoint1: CGPointMake(-18.72, -36.82), controlPoint2: CGPointMake(-17.51, -35.61))
        bezierPath.addLineToPoint(CGPointMake(-17.51, -20.22))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, -17.51), controlPoint1: CGPointMake(-17.51, -18.72), controlPoint2: CGPointMake(-18.72, -17.51))
        bezierPath.addCurveToPoint(CGPointMake(-22.92, -20.22), controlPoint1: CGPointMake(-21.71, -17.51), controlPoint2: CGPointMake(-22.92, -18.72))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-20.22, -17.51))
        bezierPath.addLineToPoint(CGPointMake(-34.12, -17.51))
        bezierPath.addCurveToPoint(CGPointMake(-36.82, -20.22), controlPoint1: CGPointMake(-35.61, -17.51), controlPoint2: CGPointMake(-36.82, -18.72))
        bezierPath.addCurveToPoint(CGPointMake(-34.12, -22.92), controlPoint1: CGPointMake(-36.82, -21.71), controlPoint2: CGPointMake(-35.61, -22.92))
        bezierPath.addLineToPoint(CGPointMake(-20.22, -22.92))
        bezierPath.addCurveToPoint(CGPointMake(-17.51, -20.22), controlPoint1: CGPointMake(-18.72, -22.92), controlPoint2: CGPointMake(-17.51, -21.71))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, -17.51), controlPoint1: CGPointMake(-17.51, -18.72), controlPoint2: CGPointMake(-18.72, -17.51))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(35.31, -31.48))
        bezierPath.addLineToPoint(CGPointMake(-31.48, 35.31))
        bezierPath.addCurveToPoint(CGPointMake(-35.31, 35.31), controlPoint1: CGPointMake(-32.54, 36.37), controlPoint2: CGPointMake(-34.25, 36.37))
        bezierPath.addCurveToPoint(CGPointMake(-35.31, 31.48), controlPoint1: CGPointMake(-36.37, 34.25), controlPoint2: CGPointMake(-36.37, 32.54))
        bezierPath.addLineToPoint(CGPointMake(31.48, -35.31))
        bezierPath.addCurveToPoint(CGPointMake(35.31, -35.31), controlPoint1: CGPointMake(32.54, -36.37), controlPoint2: CGPointMake(34.25, -36.37))
        bezierPath.addCurveToPoint(CGPointMake(35.31, -31.48), controlPoint1: CGPointMake(36.37, -34.25), controlPoint2: CGPointMake(36.37, -32.54))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-17.51, 20.04))
        bezierPath.addLineToPoint(CGPointMake(-17.51, 33.94))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, 36.64), controlPoint1: CGPointMake(-17.51, 35.43), controlPoint2: CGPointMake(-18.72, 36.64))
        bezierPath.addCurveToPoint(CGPointMake(-22.92, 33.94), controlPoint1: CGPointMake(-21.71, 36.64), controlPoint2: CGPointMake(-22.92, 35.43))
        bezierPath.addLineToPoint(CGPointMake(-22.92, 20.04))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, 17.33), controlPoint1: CGPointMake(-22.92, 18.54), controlPoint2: CGPointMake(-21.71, 17.33))
        bezierPath.addCurveToPoint(CGPointMake(-17.51, 20.04), controlPoint1: CGPointMake(-18.72, 17.33), controlPoint2: CGPointMake(-17.51, 18.54))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-20.22, 22.74))
        bezierPath.addLineToPoint(CGPointMake(-34.12, 22.74))
        bezierPath.addCurveToPoint(CGPointMake(-36.82, 20.04), controlPoint1: CGPointMake(-35.61, 22.74), controlPoint2: CGPointMake(-36.82, 21.53))
        bezierPath.addCurveToPoint(CGPointMake(-34.12, 17.33), controlPoint1: CGPointMake(-36.82, 18.54), controlPoint2: CGPointMake(-35.61, 17.33))
        bezierPath.addLineToPoint(CGPointMake(-20.22, 17.33))
        bezierPath.addCurveToPoint(CGPointMake(-17.51, 20.04), controlPoint1: CGPointMake(-18.72, 17.33), controlPoint2: CGPointMake(-17.51, 18.54))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, 22.74), controlPoint1: CGPointMake(-17.51, 21.53), controlPoint2: CGPointMake(-18.72, 22.74))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(20.04, -22.92))
        bezierPath.addLineToPoint(CGPointMake(33.94, -22.92))
        bezierPath.addCurveToPoint(CGPointMake(36.64, -20.22), controlPoint1: CGPointMake(35.43, -22.92), controlPoint2: CGPointMake(36.64, -21.71))
        bezierPath.addCurveToPoint(CGPointMake(33.94, -17.51), controlPoint1: CGPointMake(36.64, -18.72), controlPoint2: CGPointMake(35.43, -17.51))
        bezierPath.addLineToPoint(CGPointMake(20.04, -17.51))
        bezierPath.addCurveToPoint(CGPointMake(17.33, -20.22), controlPoint1: CGPointMake(18.54, -17.51), controlPoint2: CGPointMake(17.33, -18.72))
        bezierPath.addCurveToPoint(CGPointMake(20.04, -22.92), controlPoint1: CGPointMake(17.33, -21.71), controlPoint2: CGPointMake(18.54, -22.92))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(17.33, -20.22))
        bezierPath.addLineToPoint(CGPointMake(17.33, -34.12))
        bezierPath.addCurveToPoint(CGPointMake(20.04, -36.82), controlPoint1: CGPointMake(17.33, -35.61), controlPoint2: CGPointMake(18.54, -36.82))
        bezierPath.addCurveToPoint(CGPointMake(22.74, -34.12), controlPoint1: CGPointMake(21.53, -36.82), controlPoint2: CGPointMake(22.74, -35.61))
        bezierPath.addLineToPoint(CGPointMake(22.74, -20.22))
        bezierPath.addCurveToPoint(CGPointMake(20.04, -17.51), controlPoint1: CGPointMake(22.74, -18.72), controlPoint2: CGPointMake(21.53, -17.51))
        bezierPath.addCurveToPoint(CGPointMake(17.33, -20.22), controlPoint1: CGPointMake(18.54, -17.51), controlPoint2: CGPointMake(17.33, -18.72))
        bezierPath.closePath()
        VaavudStyle.vaavudDarkGrey.setFill()
        bezierPath.fill()

        CGContextRestoreGState(context)
    }

    public class func drawCompassArrow(#frame: CGRect, strokeColor: UIColor, strokeWidth: CGFloat) {

        //// Circle Drawing
        var circlePath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 4, frame.minY + 4, frame.width - 8, frame.height - 8))
        strokeColor.setStroke()
        circlePath.lineWidth = strokeWidth
        circlePath.stroke()


        //// Body Drawing
        var bodyPath = UIBezierPath()
        bodyPath.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.30000 * frame.height))
        bodyPath.addLineToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.85000 * frame.height))
        strokeColor.setStroke()
        bodyPath.lineWidth = strokeWidth
        bodyPath.stroke()


        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.15000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41000 * frame.width, frame.minY + 0.35000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59000 * frame.width, frame.minY + 0.35000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.15000 * frame.height))
        bezierPath.closePath()
        bezierPath.lineCapStyle = kCGLineCapSquare;

        strokeColor.setFill()
        bezierPath.fill()
        strokeColor.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()
    }

    public class func drawSleipnirCompass(#frame: CGRect, strokeColor: UIColor, strokeWidth: CGFloat, detailStrokeWidth: CGFloat) {

        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49910 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49910 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49910 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49910 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49910 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49910 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49910 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59510 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59510 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59510 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.47931 * frame.width, frame.minY + 0.68153 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48018 * frame.width, frame.minY + 0.73626 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.52405 * frame.width, frame.minY + 0.73539 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.52492 * frame.width, frame.minY + 0.68066 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.52141 * frame.width, frame.minY + 0.74581 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.52141 * frame.width, frame.minY + 0.73539 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.48282 * frame.width, frame.minY + 0.73539 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48282 * frame.width, frame.minY + 0.74581 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51703 * frame.width, frame.minY + 0.76666 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51703 * frame.width, frame.minY + 0.74581 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51703 * frame.width, frame.minY + 0.81618 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51703 * frame.width, frame.minY + 0.79794 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51527 * frame.width, frame.minY + 0.81705 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51615 * frame.width, frame.minY + 0.81618 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51703 * frame.width, frame.minY + 0.79186 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51703 * frame.width, frame.minY + 0.77274 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51615 * frame.width, frame.minY + 0.77274 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51615 * frame.width, frame.minY + 0.76666 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51615 * frame.width, frame.minY + 0.79794 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51615 * frame.width, frame.minY + 0.79186 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.48720 * frame.width, frame.minY + 0.74581 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48720 * frame.width, frame.minY + 0.76666 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48808 * frame.width, frame.minY + 0.76666 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48808 * frame.width, frame.minY + 0.77274 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48720 * frame.width, frame.minY + 0.77274 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48720 * frame.width, frame.minY + 0.79186 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48808 * frame.width, frame.minY + 0.79186 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48808 * frame.width, frame.minY + 0.79794 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48720 * frame.width, frame.minY + 0.79794 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48720 * frame.width, frame.minY + 0.81618 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51264 * frame.width, frame.minY + 0.82747 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51527 * frame.width, frame.minY + 0.82487 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51527 * frame.width, frame.minY + 0.82487 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51527 * frame.width, frame.minY + 0.82313 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51527 * frame.width, frame.minY + 0.82313 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51527 * frame.width, frame.minY + 0.81705 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.48896 * frame.width, frame.minY + 0.85266 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.49773 * frame.width, frame.minY + 0.86309 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50562 * frame.width, frame.minY + 0.86309 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51440 * frame.width, frame.minY + 0.85266 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.51440 * frame.width, frame.minY + 0.85266 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.51264 * frame.width, frame.minY + 0.82660 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.48720 * frame.width, frame.minY + 0.81618 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48808 * frame.width, frame.minY + 0.81705 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48896 * frame.width, frame.minY + 0.81705 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48896 * frame.width, frame.minY + 0.82313 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48808 * frame.width, frame.minY + 0.82313 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48808 * frame.width, frame.minY + 0.82487 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.49071 * frame.width, frame.minY + 0.82747 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.48896 * frame.width, frame.minY + 0.85353 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.41088 * frame.width, frame.minY + 0.49389 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59335 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59510 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59598 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.68546 * frame.width, frame.minY + 0.18290 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.68107 * frame.width, frame.minY + 0.18116 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.68458 * frame.width, frame.minY + 0.18203 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.68283 * frame.width, frame.minY + 0.18116 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.50345 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.41264 * frame.width, frame.minY + 0.52777 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.51127 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.51995 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59159 * frame.width, frame.minY + 0.52777 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.59510 * frame.width, frame.minY + 0.50345 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.51995 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.59510 * frame.width, frame.minY + 0.51214 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.52931 * frame.width, frame.minY + 0.67458 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.59159 * frame.width, frame.minY + 0.52777 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.55563 * frame.width, frame.minY + 0.62854 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.57668 * frame.width, frame.minY + 0.57902 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.41264 * frame.width, frame.minY + 0.52777 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.47492 * frame.width, frame.minY + 0.67458 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.42667 * frame.width, frame.minY + 0.57902 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.44773 * frame.width, frame.minY + 0.62854 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.58721 * frame.width, frame.minY + 0.50345 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.58545 * frame.width, frame.minY + 0.50171 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.58633 * frame.width, frame.minY + 0.50345 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.58545 * frame.width, frame.minY + 0.50258 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.41790 * frame.width, frame.minY + 0.50171 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.41615 * frame.width, frame.minY + 0.50345 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.41790 * frame.width, frame.minY + 0.50258 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.41702 * frame.width, frame.minY + 0.50345 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.47492 * frame.width, frame.minY + 0.67458 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.47843 * frame.width, frame.minY + 0.68153 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.52492 * frame.width, frame.minY + 0.68153 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.52931 * frame.width, frame.minY + 0.67458 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.52668 * frame.width, frame.minY + 0.67892 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52755 * frame.width, frame.minY + 0.67719 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.77622 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.72062 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.75798 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.73886 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.82573 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.82747 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.52405 * frame.width, frame.minY + 0.73539 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.47931 * frame.width, frame.minY + 0.73539 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.50913 * frame.width, frame.minY + 0.73539 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.49422 * frame.width, frame.minY + 0.73539 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.52141 * frame.width, frame.minY + 0.74581 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.48369 * frame.width, frame.minY + 0.74581 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.50913 * frame.width, frame.minY + 0.74581 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.49597 * frame.width, frame.minY + 0.74581 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50562 * frame.width, frame.minY + 0.86309 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.49773 * frame.width, frame.minY + 0.86309 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.50299 * frame.width, frame.minY + 0.86309 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.50036 * frame.width, frame.minY + 0.86309 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.46870 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.41088 * frame.width, frame.minY + 0.49389 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.42580 * frame.width, frame.minY + 0.46957 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.41088 * frame.width, frame.minY + 0.49389 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41088 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41088 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41088 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49997 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.53282 * frame.width, frame.minY + 0.49997 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.47141 * frame.width, frame.minY + 0.49997 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.69423 * frame.width, frame.minY + 0.20375 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.68546 * frame.width, frame.minY + 0.18377 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.69423 * frame.width, frame.minY + 0.19593 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.69072 * frame.width, frame.minY + 0.18898 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.60651 * frame.width, frame.minY + 0.48434 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.69423 * frame.width, frame.minY + 0.20375 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.66967 * frame.width, frame.minY + 0.40355 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.70037 * frame.width, frame.minY + 0.30539 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59686 * frame.width, frame.minY + 0.49476 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.60037 * frame.width, frame.minY + 0.49216 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.60387 * frame.width, frame.minY + 0.48868 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.60738 * frame.width, frame.minY + 0.48434 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.61002 * frame.width, frame.minY + 0.26716 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.55299 * frame.width, frame.minY + 0.26108 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.59072 * frame.width, frame.minY + 0.26456 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.57229 * frame.width, frame.minY + 0.26282 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54422 * frame.width, frame.minY + 0.25153 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54773 * frame.width, frame.minY + 0.26021 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54510 * frame.width, frame.minY + 0.25674 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54422 * frame.width, frame.minY + 0.25239 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54422 * frame.width, frame.minY + 0.20809 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54422 * frame.width, frame.minY + 0.23763 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54422 * frame.width, frame.minY + 0.22286 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.55387 * frame.width, frame.minY + 0.19854 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54510 * frame.width, frame.minY + 0.20288 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54861 * frame.width, frame.minY + 0.19940 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.66089 * frame.width, frame.minY + 0.20722 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.58984 * frame.width, frame.minY + 0.20027 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.62493 * frame.width, frame.minY + 0.20288 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.66879 * frame.width, frame.minY + 0.21591 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.66528 * frame.width, frame.minY + 0.20809 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.66879 * frame.width, frame.minY + 0.21157 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.66791 * frame.width, frame.minY + 0.26543 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.66967 * frame.width, frame.minY + 0.23241 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.66967 * frame.width, frame.minY + 0.24892 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.65651 * frame.width, frame.minY + 0.27411 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.66704 * frame.width, frame.minY + 0.27151 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.66265 * frame.width, frame.minY + 0.27411 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.60826 * frame.width, frame.minY + 0.26716 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.64072 * frame.width, frame.minY + 0.27151 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.62493 * frame.width, frame.minY + 0.26890 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50124 * frame.width, frame.minY + 0.16900 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.68107 * frame.width, frame.minY + 0.18029 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.56177 * frame.width, frame.minY + 0.16900 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.62142 * frame.width, frame.minY + 0.17334 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.67756 * frame.width, frame.minY + 0.18029 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.59072 * frame.width, frame.minY + 0.17247 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.64861 * frame.width, frame.minY + 0.17682 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.61966 * frame.width, frame.minY + 0.17421 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59159 * frame.width, frame.minY + 0.17247 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.56966 * frame.width, frame.minY + 0.17161 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.56966 * frame.width, frame.minY + 0.17161 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.53633 * frame.width, frame.minY + 0.16987 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.55826 * frame.width, frame.minY + 0.17161 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54685 * frame.width, frame.minY + 0.17074 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.66791 * frame.width, frame.minY + 0.17942 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.53633 * frame.width, frame.minY + 0.16987 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.62405 * frame.width, frame.minY + 0.17421 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.58019 * frame.width, frame.minY + 0.17161 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.66879 * frame.width, frame.minY + 0.17942 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.66791 * frame.width, frame.minY + 0.17942 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.67756 * frame.width, frame.minY + 0.18029 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.66879 * frame.width, frame.minY + 0.17942 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.67493 * frame.width, frame.minY + 0.18029 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67142 * frame.width, frame.minY + 0.17942 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.52405 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50211 * frame.width, frame.minY + 0.16987 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.51703 * frame.width, frame.minY + 0.16987 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.51001 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.53545 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.52405 * frame.width, frame.minY + 0.16987 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.53194 * frame.width, frame.minY + 0.16987 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52843 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50124 * frame.width, frame.minY + 0.16900 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.50211 * frame.width, frame.minY + 0.16900 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59335 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59335 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.47931 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50124 * frame.width, frame.minY + 0.16987 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48632 * frame.width, frame.minY + 0.16987 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.49334 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46878 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.46878 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.47141 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.47492 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.47931 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.32316 * frame.width, frame.minY + 0.18116 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.32667 * frame.width, frame.minY + 0.18029 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.16987 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.46870 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.26716 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.37141 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.31088 * frame.width, frame.minY + 0.20375 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.39860 * frame.width, frame.minY + 0.48347 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.30474 * frame.width, frame.minY + 0.30539 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.33544 * frame.width, frame.minY + 0.40268 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.32316 * frame.width, frame.minY + 0.18116 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.31088 * frame.width, frame.minY + 0.20375 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.31526 * frame.width, frame.minY + 0.18551 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.31088 * frame.width, frame.minY + 0.19419 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.32667 * frame.width, frame.minY + 0.18029 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.33544 * frame.width, frame.minY + 0.17942 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.32930 * frame.width, frame.minY + 0.18029 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.33281 * frame.width, frame.minY + 0.17942 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.33632 * frame.width, frame.minY + 0.17942 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.16987 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.38018 * frame.width, frame.minY + 0.17421 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.42404 * frame.width, frame.minY + 0.17161 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.33544 * frame.width, frame.minY + 0.17942 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.33632 * frame.width, frame.minY + 0.17942 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.39772 * frame.width, frame.minY + 0.48347 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40036 * frame.width, frame.minY + 0.48694 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40386 * frame.width, frame.minY + 0.49042 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40737 * frame.width, frame.minY + 0.49302 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.49389 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49650 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.41001 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.47843 * frame.width, frame.minY + 0.68153 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50211 * frame.width, frame.minY + 0.68153 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48632 * frame.width, frame.minY + 0.68153 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.49422 * frame.width, frame.minY + 0.68153 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50211 * frame.width, frame.minY + 0.68153 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.52580 * frame.width, frame.minY + 0.68153 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.51001 * frame.width, frame.minY + 0.68153 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.51791 * frame.width, frame.minY + 0.68153 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.68674 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.77014 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.71454 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.74234 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.77101 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54159 * frame.width, frame.minY + 0.82747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.79012 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.80836 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.82747 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.83182 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.83182 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54159 * frame.width, frame.minY + 0.83616 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.83355 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.83529 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.77101 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.82747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.79012 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.80836 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.68587 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.68761 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.64852 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.68501 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.66068 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.67284 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.77622 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.76753 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.77361 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.77014 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.68587 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.64939 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.67371 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.54335 * frame.width, frame.minY + 0.66155 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46088 * frame.width, frame.minY + 0.68587 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46088 * frame.width, frame.minY + 0.64939 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.46088 * frame.width, frame.minY + 0.67371 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46088 * frame.width, frame.minY + 0.66155 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46088 * frame.width, frame.minY + 0.68674 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.46088 * frame.width, frame.minY + 0.68501 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.77014 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46088 * frame.width, frame.minY + 0.68674 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.74234 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.71454 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.82747 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.77101 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.80836 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.79012 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.77101 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.78317 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.77535 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.77883 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.83095 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.82747 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46264 * frame.width, frame.minY + 0.83616 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.83095 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.46264 * frame.width, frame.minY + 0.83442 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.83268 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.54247 * frame.width, frame.minY + 0.83182 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50475 * frame.width, frame.minY + 0.86483 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54159 * frame.width, frame.minY + 0.85527 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52843 * frame.width, frame.minY + 0.86656 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.49948 * frame.width, frame.minY + 0.86483 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.83095 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.47492 * frame.width, frame.minY + 0.86656 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46176 * frame.width, frame.minY + 0.85527 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50475 * frame.width, frame.minY + 0.86483 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.50211 * frame.width, frame.minY + 0.86483 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50211 * frame.width, frame.minY + 0.86483 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.49948 * frame.width, frame.minY + 0.86483 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.53720 * frame.width, frame.minY + 0.47131 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49563 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.57756 * frame.width, frame.minY + 0.47565 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59422 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59510 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.59510 * frame.width, frame.minY + 0.49563 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.59510 * frame.width, frame.minY + 0.50345 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50211 * frame.width, frame.minY + 0.50345 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.56440 * frame.width, frame.minY + 0.50345 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.53282 * frame.width, frame.minY + 0.50345 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50211 * frame.width, frame.minY + 0.50345 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.40913 * frame.width, frame.minY + 0.50345 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.47141 * frame.width, frame.minY + 0.50345 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.44071 * frame.width, frame.minY + 0.50345 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.31439 * frame.width, frame.minY + 0.28454 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.26890 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.31702 * frame.width, frame.minY + 0.28454 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.43632 * frame.width, frame.minY + 0.26456 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.31965 * frame.width, frame.minY + 0.32102 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.29844 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.31965 * frame.width, frame.minY + 0.32102 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.42053 * frame.width, frame.minY + 0.29496 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.32930 * frame.width, frame.minY + 0.35577 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.32884 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.32930 * frame.width, frame.minY + 0.35577 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.39948 * frame.width, frame.minY + 0.32537 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.34246 * frame.width, frame.minY + 0.38965 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46878 * frame.width, frame.minY + 0.35751 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.34246 * frame.width, frame.minY + 0.38965 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.39685 * frame.width, frame.minY + 0.35751 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.35825 * frame.width, frame.minY + 0.42092 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46878 * frame.width, frame.minY + 0.38791 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.35825 * frame.width, frame.minY + 0.42092 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.41088 * frame.width, frame.minY + 0.38444 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.37579 * frame.width, frame.minY + 0.45133 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46878 * frame.width, frame.minY + 0.41745 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.37579 * frame.width, frame.minY + 0.45133 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.42667 * frame.width, frame.minY + 0.41224 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.39509 * frame.width, frame.minY + 0.47999 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.44611 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.39509 * frame.width, frame.minY + 0.47999 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.42316 * frame.width, frame.minY + 0.44264 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.46790 * frame.width, frame.minY + 0.46870 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.53720 * frame.width, frame.minY + 0.47044 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.46878 * frame.width, frame.minY + 0.46870 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52141 * frame.width, frame.minY + 0.46870 * frame.height))
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.31000 * frame.width, frame.minY + 0.21070 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.46703 * frame.width, frame.minY + 0.20027 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.31000 * frame.width, frame.minY + 0.21070 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.37053 * frame.width, frame.minY + 0.20201 * frame.height))
        strokeColor.setStroke()
        bezierPath.lineWidth = detailStrokeWidth
        bezierPath.stroke()


        //// Circle Drawing
        var circlePath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 4, frame.minY + 4, frame.width - 8, frame.height - 8))
        strokeColor.setStroke()
        circlePath.lineWidth = strokeWidth
        circlePath.stroke()
    }

    //// Generated Images

    public class func imageOfSleipnirCompass(#frame: CGRect, strokeColor: UIColor, strokeWidth: CGFloat, detailStrokeWidth: CGFloat) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            VaavudStyle.drawSleipnirCompass(frame: frame, strokeColor: strokeColor, strokeWidth: strokeWidth, detailStrokeWidth: detailStrokeWidth)

        let imageOfSleipnirCompass = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfSleipnirCompass
    }

}



extension UIColor {
    func colorWithHue(newHue: CGFloat) -> UIColor {
        var saturation: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(nil, saturation: &saturation, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: newHue, saturation: saturation, brightness: brightness, alpha: alpha)
    }
    func colorWithSaturation(newSaturation: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: nil, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: hue, saturation: newSaturation, brightness: brightness, alpha: alpha)
    }
    func colorWithBrightness(newBrightness: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: nil, alpha: &alpha)
        return UIColor(hue: hue, saturation: saturation, brightness: newBrightness, alpha: alpha)
    }
    func colorWithAlpha(newAlpha: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, brightness: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: nil)
        return UIColor(hue: hue, saturation: saturation, brightness: brightness, alpha: newAlpha)
    }
    func colorWithHighlight(highlight: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-highlight) + highlight, green: green * (1-highlight) + highlight, blue: blue * (1-highlight) + highlight, alpha: alpha * (1-highlight) + highlight)
    }
    func colorWithShadow(shadow: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-shadow), green: green * (1-shadow), blue: blue * (1-shadow), alpha: alpha * (1-shadow) + shadow)
    }
}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
