//
//  VaavudStyle.swift
//  Vaavud
//
//  Created by Grustaf on 23/01/15.
//  Copyright (c) 2015 Vaavud. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class VaavudStyle : NSObject {

    //// Cache

    private struct Cache {
        static var vaavudRed: UIColor = UIColor(red: 0.820, green: 0.165, blue: 0.184, alpha: 1.000)
        static var vaavudBlue: UIColor = UIColor(red: 0.000, green: 0.631, blue: 0.882, alpha: 1.000)
        static var vaavudDarkGrey: UIColor = UIColor(red: 0.188, green: 0.243, blue: 0.282, alpha: 1.000)
        static var vaavudLightGrey: UIColor = UIColor(red: 0.478, green: 0.525, blue: 0.549, alpha: 1.000)
    }

    //// Colors

    public class var vaavudRed: UIColor { return Cache.vaavudRed }
    public class var vaavudBlue: UIColor { return Cache.vaavudBlue }
    public class var vaavudDarkGrey: UIColor { return Cache.vaavudDarkGrey }
    public class var vaavudLightGrey: UIColor { return Cache.vaavudLightGrey }

    //// Drawing Methods

    public class func drawVaavudTemperature(#height: CGFloat, reading: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let scale: CGFloat = height / 100.0
        let tempGaugeYOffset: CGFloat = 61 - 0.5 * reading * 100

        //// Bezier 2 Drawing
        CGContextSaveGState(context)
        CGContextScaleCTM(context, scale, scale)

        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(29.97, 64.86))
        bezier2Path.addLineToPoint(CGPointMake(29.97, 13.08))
        bezier2Path.addCurveToPoint(CGPointMake(21.9, 5.45), controlPoint1: CGPointMake(29.97, 8.84), controlPoint2: CGPointMake(26.34, 5.45))
        bezier2Path.addCurveToPoint(CGPointMake(13.83, 13.08), controlPoint1: CGPointMake(17.42, 5.45), controlPoint2: CGPointMake(13.83, 8.88))
        bezier2Path.addLineToPoint(CGPointMake(13.83, 64.67))
        bezier2Path.addCurveToPoint(CGPointMake(12.63, 66.89), controlPoint1: CGPointMake(13.83, 65.55), controlPoint2: CGPointMake(13.39, 66.37))
        bezier2Path.addCurveToPoint(CGPointMake(5.76, 79.39), controlPoint1: CGPointMake(8.34, 69.81), controlPoint2: CGPointMake(5.76, 74.35))
        bezier2Path.addCurveToPoint(CGPointMake(21.9, 94.65), controlPoint1: CGPointMake(5.76, 87.88), controlPoint2: CGPointMake(12.93, 94.65))
        bezier2Path.addCurveToPoint(CGPointMake(38.04, 79.39), controlPoint1: CGPointMake(30.87, 94.65), controlPoint2: CGPointMake(38.04, 87.88))
        bezier2Path.addCurveToPoint(CGPointMake(31.17, 67.07), controlPoint1: CGPointMake(38.04, 74.51), controlPoint2: CGPointMake(35.44, 69.98))
        bezier2Path.addCurveToPoint(CGPointMake(29.97, 64.86), controlPoint1: CGPointMake(30.41, 66.56), controlPoint2: CGPointMake(29.97, 65.73))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(35.73, 64.86))
        bezier2Path.addLineToPoint(CGPointMake(34.53, 62.64))
        bezier2Path.addCurveToPoint(CGPointMake(43.8, 79.39), controlPoint1: CGPointMake(40.27, 66.55), controlPoint2: CGPointMake(43.8, 72.71))
        bezier2Path.addCurveToPoint(CGPointMake(21.9, 100.1), controlPoint1: CGPointMake(43.8, 90.89), controlPoint2: CGPointMake(34.06, 100.1))
        bezier2Path.addCurveToPoint(CGPointMake(0, 79.39), controlPoint1: CGPointMake(9.74, 100.1), controlPoint2: CGPointMake(0, 90.89))
        bezier2Path.addCurveToPoint(CGPointMake(9.27, 62.46), controlPoint1: CGPointMake(0, 72.56), controlPoint2: CGPointMake(3.5, 66.39))
        bezier2Path.addLineToPoint(CGPointMake(8.07, 64.67))
        bezier2Path.addLineToPoint(CGPointMake(8.07, 13.08))
        bezier2Path.addCurveToPoint(CGPointMake(21.9, -0), controlPoint1: CGPointMake(8.07, 5.89), controlPoint2: CGPointMake(14.22, -0))
        bezier2Path.addCurveToPoint(CGPointMake(35.73, 13.08), controlPoint1: CGPointMake(29.51, -0), controlPoint2: CGPointMake(35.73, 5.82))
        bezier2Path.addLineToPoint(CGPointMake(35.73, 64.86))
        bezier2Path.closePath()
        VaavudStyle.vaavudDarkGrey.setFill()
        bezier2Path.fill()

        CGContextRestoreGState(context)


        //// Bezier Drawing
        CGContextSaveGState(context)
        CGContextScaleCTM(context, scale, scale)

        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(26.13, (tempGaugeYOffset - 0.002)))
        bezierPath.addCurveToPoint(CGPointMake(26.13, 68.13), controlPoint1: CGPointMake(26.13, (tempGaugeYOffset - 0.002) - 0), controlPoint2: CGPointMake(26.13, 62.98))
        bezierPath.addLineToPoint(CGPointMake(29.01, 69.94))
        bezierPath.addCurveToPoint(CGPointMake(34, 79.39), controlPoint1: CGPointMake(32.27, 72.12), controlPoint2: CGPointMake(34.19, 75.76))
        bezierPath.addCurveToPoint(CGPointMake(21.71, 91.02), controlPoint1: CGPointMake(34, 85.75), controlPoint2: CGPointMake(28.43, 91.02))
        bezierPath.addCurveToPoint(CGPointMake(9.41, 79.39), controlPoint1: CGPointMake(14.98, 91.02), controlPoint2: CGPointMake(9.41, 85.75))
        bezierPath.addCurveToPoint(CGPointMake(14.6, 69.94), controlPoint1: CGPointMake(9.41, 75.76), controlPoint2: CGPointMake(11.33, 72.12))
        bezierPath.addLineToPoint(CGPointMake(17.48, 68.13))
        bezierPath.addCurveToPoint(CGPointMake(17.48, (tempGaugeYOffset + 0.001)), controlPoint1: CGPointMake(17.48, 62.98), controlPoint2: CGPointMake(17.48, (tempGaugeYOffset + 0.001)))
        bezierPath.addLineToPoint(CGPointMake(26.13, (tempGaugeYOffset + 0.001)))
        bezierPath.addLineToPoint(CGPointMake(26.13, (tempGaugeYOffset - 0.002)))
        bezierPath.closePath()
        VaavudStyle.vaavudDarkGrey.setFill()
        bezierPath.fill()

        CGContextRestoreGState(context)
    }

    public class func drawVaavudPressure(#height: CGFloat, reading: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let scale: CGFloat = height / 100.0
        let pressureGaugeCenterX: CGFloat = 50 * scale
        let pressureGaugeCenterY: CGFloat = 50 * scale
        let pressureGaugeRotation: CGFloat = -175 - 280 * reading

        //// Oval 4 Drawing
        CGContextSaveGState(context)
        CGContextScaleCTM(context, scale, scale)

        var oval4Path = UIBezierPath(ovalInRect: CGRectMake(36.1, 36.1, 28.2, 28.2))
        VaavudStyle.vaavudDarkGrey.setFill()
        oval4Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, pressureGaugeCenterX, pressureGaugeCenterY)
        CGContextRotateCTM(context, -pressureGaugeRotation * CGFloat(M_PI) / 180)
        CGContextScaleCTM(context, scale, scale)

        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(27.86, -27.75))
        bezier2Path.addLineToPoint(CGPointMake(-21.72, 11.81))
        bezier2Path.addLineToPoint(CGPointMake(-11.5, 22.03))
        bezier2Path.addLineToPoint(CGPointMake(27.86, -27.75))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        VaavudStyle.vaavudDarkGrey.setFill()
        bezier2Path.fill()

        CGContextRestoreGState(context)


        //// Oval 3 Drawing
        CGContextSaveGState(context)
        CGContextScaleCTM(context, scale, scale)

        var oval3Path = UIBezierPath()
        oval3Path.moveToPoint(CGPointMake(94.58, 50))
        oval3Path.addCurveToPoint(CGPointMake(50, 5.42), controlPoint1: CGPointMake(94.58, 25.38), controlPoint2: CGPointMake(74.62, 5.42))
        oval3Path.addCurveToPoint(CGPointMake(5.42, 50), controlPoint1: CGPointMake(25.38, 5.42), controlPoint2: CGPointMake(5.42, 25.38))
        oval3Path.addCurveToPoint(CGPointMake(50, 94.58), controlPoint1: CGPointMake(5.42, 74.62), controlPoint2: CGPointMake(25.38, 94.58))
        oval3Path.addCurveToPoint(CGPointMake(94.58, 50), controlPoint1: CGPointMake(74.62, 94.58), controlPoint2: CGPointMake(94.58, 74.62))
        oval3Path.closePath()
        oval3Path.moveToPoint(CGPointMake(100, 50))
        oval3Path.addCurveToPoint(CGPointMake(50, 100), controlPoint1: CGPointMake(100, 77.61), controlPoint2: CGPointMake(77.61, 100))
        oval3Path.addCurveToPoint(CGPointMake(0, 50), controlPoint1: CGPointMake(22.39, 100), controlPoint2: CGPointMake(-0, 77.61))
        oval3Path.addCurveToPoint(CGPointMake(50, 0), controlPoint1: CGPointMake(0, 22.39), controlPoint2: CGPointMake(22.39, 0))
        oval3Path.addCurveToPoint(CGPointMake(100, 50), controlPoint1: CGPointMake(77.61, 0), controlPoint2: CGPointMake(100, 22.39))
        oval3Path.closePath()
        VaavudStyle.vaavudDarkGrey.setFill()
        oval3Path.fill()

        CGContextRestoreGState(context)
    }

    public class func drawVaavudGustiness(#height: CGFloat, reading: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let scale: CGFloat = height / 100.0
        let gustinessCenterX: CGFloat = 50 * scale
        let gustinessCenterY: CGFloat = 50 * scale
        let gustinessRotation: CGFloat = -reading * 360

        //// Bezier 3 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, gustinessCenterX, gustinessCenterY)
        CGContextRotateCTM(context, -gustinessRotation * CGFloat(M_PI) / 180)
        CGContextScaleCTM(context, scale, scale)

        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(-42.13, 25.65))
        bezier3Path.addCurveToPoint(CGPointMake(-17.03, -36.01), controlPoint1: CGPointMake(-52.51, 1.87), controlPoint2: CGPointMake(-41.31, -25.7))
        bezier3Path.addCurveToPoint(CGPointMake(33.52, -16), controlPoint1: CGPointMake(2.6, -44.1), controlPoint2: CGPointMake(25.16, -35.2))
        bezier3Path.addCurveToPoint(CGPointMake(17.27, 24.08), controlPoint1: CGPointMake(40.22, -0.47), controlPoint2: CGPointMake(33.01, 17.37))
        bezier3Path.addCurveToPoint(CGPointMake(-15.74, 11.12), controlPoint1: CGPointMake(4.56, 29.46), controlPoint2: CGPointMake(-10.26, 23.63))
        bezier3Path.addCurveToPoint(CGPointMake(-4.97, -15.19), controlPoint1: CGPointMake(-20.16, 0.83), controlPoint2: CGPointMake(-15.38, -10.87))
        bezier3Path.addCurveToPoint(CGPointMake(16.73, -6.72), controlPoint1: CGPointMake(3.41, -18.73), controlPoint2: CGPointMake(13.06, -14.92))
        bezier3Path.addCurveToPoint(CGPointMake(9.64, 10.74), controlPoint1: CGPointMake(19.64, 0), controlPoint2: CGPointMake(16.51, 7.78))
        bezier3Path.addCurveToPoint(CGPointMake(-4.91, 4.96), controlPoint1: CGPointMake(4.07, 13.14), controlPoint2: CGPointMake(-2.5, 10.55))
        bezier3Path.addCurveToPoint(CGPointMake(-0.09, -6.79), controlPoint1: CGPointMake(-6.88, 0.4), controlPoint2: CGPointMake(-4.72, -4.87))
        bezier3Path.addCurveToPoint(CGPointMake(9.86, -2.98), controlPoint1: CGPointMake(3.73, -8.4), controlPoint2: CGPointMake(8.17, -6.66))
        bezier3Path.addCurveToPoint(CGPointMake(9.2, -1.26), controlPoint1: CGPointMake(10.16, -2.32), controlPoint2: CGPointMake(9.87, -1.55))
        bezier3Path.addCurveToPoint(CGPointMake(7.46, -1.9), controlPoint1: CGPointMake(8.54, -0.96), controlPoint2: CGPointMake(7.76, -1.25))
        bezier3Path.addCurveToPoint(CGPointMake(0.94, -4.39), controlPoint1: CGPointMake(6.36, -4.3), controlPoint2: CGPointMake(3.44, -5.44))
        bezier3Path.addCurveToPoint(CGPointMake(-2.48, 3.94), controlPoint1: CGPointMake(-2.35, -3.02), controlPoint2: CGPointMake(-3.88, 0.7))
        bezier3Path.addCurveToPoint(CGPointMake(8.59, 8.35), controlPoint1: CGPointMake(-0.65, 8.2), controlPoint2: CGPointMake(4.36, 10.17))
        bezier3Path.addCurveToPoint(CGPointMake(14.31, -5.68), controlPoint1: CGPointMake(14.13, 5.96), controlPoint2: CGPointMake(16.64, -0.29))
        bezier3Path.addCurveToPoint(CGPointMake(-3.94, -12.79), controlPoint1: CGPointMake(11.23, -12.57), controlPoint2: CGPointMake(3.11, -15.77))
        bezier3Path.addCurveToPoint(CGPointMake(-13.32, 10.09), controlPoint1: CGPointMake(-13.01, -9.02), controlPoint2: CGPointMake(-17.16, 1.13))
        bezier3Path.addCurveToPoint(CGPointMake(16.23, 21.69), controlPoint1: CGPointMake(-8.42, 21.27), controlPoint2: CGPointMake(4.86, 26.5))
        bezier3Path.addCurveToPoint(CGPointMake(31.1, -14.97), controlPoint1: CGPointMake(30.63, 15.54), controlPoint2: CGPointMake(37.23, -0.77))
        bezier3Path.addCurveToPoint(CGPointMake(-16, -33.61), controlPoint1: CGPointMake(23.32, -32.85), controlPoint2: CGPointMake(2.29, -41.15))
        bezier3Path.addCurveToPoint(CGPointMake(-39.71, 24.62), controlPoint1: CGPointMake(-38.93, -23.88), controlPoint2: CGPointMake(-49.51, 2.16))
        bezier3Path.addCurveToPoint(CGPointMake(-40.4, 26.33), controlPoint1: CGPointMake(-39.42, 25.28), controlPoint2: CGPointMake(-39.73, 26.05))
        bezier3Path.addCurveToPoint(CGPointMake(-42.13, 25.65), controlPoint1: CGPointMake(-41.07, 26.62), controlPoint2: CGPointMake(-41.84, 26.31))
        bezier3Path.closePath()
        VaavudStyle.vaavudDarkGrey.setFill()
        bezier3Path.fill()

        CGContextRestoreGState(context)
    }

    public class func drawVaavudWindchill(#height: CGFloat, reading: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let scale: CGFloat = height / 100.0
        let windchillCenterX: CGFloat = 50 * scale
        let windchillCenterY: CGFloat = 50 * scale
        let windchillRotation: CGFloat = -reading * 360

        //// Bezier Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, windchillCenterX, windchillCenterY)
        CGContextRotateCTM(context, -windchillRotation * CGFloat(M_PI) / 180)
        CGContextScaleCTM(context, scale, scale)

        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(-47.29, -2.71))
        bezierPath.addLineToPoint(CGPointMake(47.29, -2.71))
        bezierPath.addCurveToPoint(CGPointMake(50, 0), controlPoint1: CGPointMake(48.79, -2.71), controlPoint2: CGPointMake(50, -1.5))
        bezierPath.addCurveToPoint(CGPointMake(47.29, 2.71), controlPoint1: CGPointMake(50, 1.5), controlPoint2: CGPointMake(48.79, 2.71))
        bezierPath.addLineToPoint(CGPointMake(-47.29, 2.71))
        bezierPath.addCurveToPoint(CGPointMake(-50, 0), controlPoint1: CGPointMake(-48.79, 2.71), controlPoint2: CGPointMake(-50, 1.5))
        bezierPath.addCurveToPoint(CGPointMake(-47.29, -2.71), controlPoint1: CGPointMake(-50, -1.5), controlPoint2: CGPointMake(-48.79, -2.71))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(26.59, -1.9))
        bezierPath.addLineToPoint(CGPointMake(36.34, -11.82))
        bezierPath.addCurveToPoint(CGPointMake(40.16, -11.86), controlPoint1: CGPointMake(37.38, -12.89), controlPoint2: CGPointMake(39.1, -12.91))
        bezierPath.addCurveToPoint(CGPointMake(40.2, -8.03), controlPoint1: CGPointMake(41.23, -10.81), controlPoint2: CGPointMake(41.25, -9.1))
        bezierPath.addLineToPoint(CGPointMake(30.45, 1.9))
        bezierPath.addCurveToPoint(CGPointMake(26.62, 1.93), controlPoint1: CGPointMake(29.4, 2.96), controlPoint2: CGPointMake(27.69, 2.98))
        bezierPath.addCurveToPoint(CGPointMake(26.59, -1.9), controlPoint1: CGPointMake(25.56, 0.88), controlPoint2: CGPointMake(25.54, -0.83))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(30.43, -1.91))
        bezierPath.addLineToPoint(CGPointMake(40.18, 7.83))
        bezierPath.addCurveToPoint(CGPointMake(40.18, 11.66), controlPoint1: CGPointMake(41.24, 8.89), controlPoint2: CGPointMake(41.24, 10.6))
        bezierPath.addCurveToPoint(CGPointMake(36.35, 11.66), controlPoint1: CGPointMake(39.12, 12.72), controlPoint2: CGPointMake(37.41, 12.72))
        bezierPath.addLineToPoint(CGPointMake(26.61, 1.91))
        bezierPath.addCurveToPoint(CGPointMake(26.61, -1.91), controlPoint1: CGPointMake(25.55, 0.86), controlPoint2: CGPointMake(25.55, -0.86))
        bezierPath.addCurveToPoint(CGPointMake(30.43, -1.91), controlPoint1: CGPointMake(27.66, -2.97), controlPoint2: CGPointMake(29.38, -2.97))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-30.43, 1.91))
        bezierPath.addLineToPoint(CGPointMake(-40.36, -8.01))
        bezierPath.addCurveToPoint(CGPointMake(-40.36, -11.84), controlPoint1: CGPointMake(-41.42, -9.07), controlPoint2: CGPointMake(-41.42, -10.78))
        bezierPath.addCurveToPoint(CGPointMake(-36.53, -11.84), controlPoint1: CGPointMake(-39.3, -12.9), controlPoint2: CGPointMake(-37.59, -12.9))
        bezierPath.addLineToPoint(CGPointMake(-26.61, -1.91))
        bezierPath.addCurveToPoint(CGPointMake(-26.61, 1.91), controlPoint1: CGPointMake(-25.55, -0.86), controlPoint2: CGPointMake(-25.55, 0.86))
        bezierPath.addCurveToPoint(CGPointMake(-30.43, 1.91), controlPoint1: CGPointMake(-27.66, 2.97), controlPoint2: CGPointMake(-29.38, 2.97))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-26.62, 1.93))
        bezierPath.addLineToPoint(CGPointMake(-36.55, 11.68))
        bezierPath.addCurveToPoint(CGPointMake(-40.38, 11.64), controlPoint1: CGPointMake(-37.62, 12.73), controlPoint2: CGPointMake(-39.33, 12.71))
        bezierPath.addCurveToPoint(CGPointMake(-40.34, 7.82), controlPoint1: CGPointMake(-41.43, 10.58), controlPoint2: CGPointMake(-41.41, 8.86))
        bezierPath.addLineToPoint(CGPointMake(-30.42, -1.93))
        bezierPath.addCurveToPoint(CGPointMake(-26.59, -1.9), controlPoint1: CGPointMake(-29.35, -2.98), controlPoint2: CGPointMake(-27.64, -2.96))
        bezierPath.addCurveToPoint(CGPointMake(-26.62, 1.93), controlPoint1: CGPointMake(-25.54, -0.83), controlPoint2: CGPointMake(-25.56, 0.88))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(2.71, -47.29))
        bezierPath.addLineToPoint(CGPointMake(2.71, 47.29))
        bezierPath.addCurveToPoint(CGPointMake(0, 50), controlPoint1: CGPointMake(2.71, 48.79), controlPoint2: CGPointMake(1.5, 50))
        bezierPath.addCurveToPoint(CGPointMake(-2.71, 47.29), controlPoint1: CGPointMake(-1.5, 50), controlPoint2: CGPointMake(-2.71, 48.79))
        bezierPath.addLineToPoint(CGPointMake(-2.71, -47.29))
        bezierPath.addCurveToPoint(CGPointMake(0, -50), controlPoint1: CGPointMake(-2.71, -48.79), controlPoint2: CGPointMake(-1.5, -50))
        bezierPath.addCurveToPoint(CGPointMake(2.71, -47.29), controlPoint1: CGPointMake(1.5, -50), controlPoint2: CGPointMake(2.71, -48.79))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(1.91, 26.61))
        bezierPath.addLineToPoint(CGPointMake(11.66, 36.35))
        bezierPath.addCurveToPoint(CGPointMake(11.66, 40.18), controlPoint1: CGPointMake(12.72, 37.41), controlPoint2: CGPointMake(12.72, 39.12))
        bezierPath.addCurveToPoint(CGPointMake(7.83, 40.18), controlPoint1: CGPointMake(10.6, 41.24), controlPoint2: CGPointMake(8.89, 41.24))
        bezierPath.addLineToPoint(CGPointMake(-1.91, 30.43))
        bezierPath.addCurveToPoint(CGPointMake(-1.91, 26.61), controlPoint1: CGPointMake(-2.97, 29.38), controlPoint2: CGPointMake(-2.97, 27.66))
        bezierPath.addCurveToPoint(CGPointMake(1.91, 26.61), controlPoint1: CGPointMake(-0.86, 25.55), controlPoint2: CGPointMake(0.86, 25.55))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(1.9, 30.45))
        bezierPath.addLineToPoint(CGPointMake(-8.03, 40.2))
        bezierPath.addCurveToPoint(CGPointMake(-11.86, 40.16), controlPoint1: CGPointMake(-9.1, 41.25), controlPoint2: CGPointMake(-10.81, 41.23))
        bezierPath.addCurveToPoint(CGPointMake(-11.82, 36.34), controlPoint1: CGPointMake(-12.91, 39.1), controlPoint2: CGPointMake(-12.89, 37.38))
        bezierPath.addLineToPoint(CGPointMake(-1.9, 26.59))
        bezierPath.addCurveToPoint(CGPointMake(1.93, 26.62), controlPoint1: CGPointMake(-0.83, 25.54), controlPoint2: CGPointMake(0.88, 25.56))
        bezierPath.addCurveToPoint(CGPointMake(1.9, 30.45), controlPoint1: CGPointMake(2.98, 27.69), controlPoint2: CGPointMake(2.96, 29.4))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-1.93, -30.42))
        bezierPath.addLineToPoint(CGPointMake(7.82, -40.34))
        bezierPath.addCurveToPoint(CGPointMake(11.64, -40.38), controlPoint1: CGPointMake(8.86, -41.41), controlPoint2: CGPointMake(10.58, -41.43))
        bezierPath.addCurveToPoint(CGPointMake(11.68, -36.55), controlPoint1: CGPointMake(12.71, -39.33), controlPoint2: CGPointMake(12.73, -37.62))
        bezierPath.addLineToPoint(CGPointMake(1.93, -26.62))
        bezierPath.addCurveToPoint(CGPointMake(-1.9, -26.59), controlPoint1: CGPointMake(0.88, -25.56), controlPoint2: CGPointMake(-0.83, -25.54))
        bezierPath.addCurveToPoint(CGPointMake(-1.93, -30.42), controlPoint1: CGPointMake(-2.96, -27.64), controlPoint2: CGPointMake(-2.98, -29.35))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-1.91, -26.61))
        bezierPath.addLineToPoint(CGPointMake(-11.84, -36.53))
        bezierPath.addCurveToPoint(CGPointMake(-11.84, -40.36), controlPoint1: CGPointMake(-12.9, -37.59), controlPoint2: CGPointMake(-12.9, -39.3))
        bezierPath.addCurveToPoint(CGPointMake(-8.01, -40.36), controlPoint1: CGPointMake(-10.78, -41.42), controlPoint2: CGPointMake(-9.07, -41.42))
        bezierPath.addLineToPoint(CGPointMake(1.91, -30.43))
        bezierPath.addCurveToPoint(CGPointMake(1.91, -26.61), controlPoint1: CGPointMake(2.97, -29.38), controlPoint2: CGPointMake(2.97, -27.66))
        bezierPath.addCurveToPoint(CGPointMake(-1.91, -26.61), controlPoint1: CGPointMake(0.86, -25.55), controlPoint2: CGPointMake(-0.86, -25.55))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-31.48, -35.31))
        bezierPath.addLineToPoint(CGPointMake(35.31, 31.48))
        bezierPath.addCurveToPoint(CGPointMake(35.31, 35.31), controlPoint1: CGPointMake(36.37, 32.54), controlPoint2: CGPointMake(36.37, 34.25))
        bezierPath.addCurveToPoint(CGPointMake(31.48, 35.31), controlPoint1: CGPointMake(34.25, 36.37), controlPoint2: CGPointMake(32.54, 36.37))
        bezierPath.addLineToPoint(CGPointMake(-35.31, -31.48))
        bezierPath.addCurveToPoint(CGPointMake(-35.31, -35.31), controlPoint1: CGPointMake(-36.37, -32.54), controlPoint2: CGPointMake(-36.37, -34.25))
        bezierPath.addCurveToPoint(CGPointMake(-31.48, -35.31), controlPoint1: CGPointMake(-34.25, -36.37), controlPoint2: CGPointMake(-32.54, -36.37))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(20.04, 17.33))
        bezierPath.addLineToPoint(CGPointMake(33.94, 17.33))
        bezierPath.addCurveToPoint(CGPointMake(36.64, 20.04), controlPoint1: CGPointMake(35.43, 17.33), controlPoint2: CGPointMake(36.64, 18.54))
        bezierPath.addCurveToPoint(CGPointMake(33.94, 22.74), controlPoint1: CGPointMake(36.64, 21.53), controlPoint2: CGPointMake(35.43, 22.74))
        bezierPath.addLineToPoint(CGPointMake(20.04, 22.74))
        bezierPath.addCurveToPoint(CGPointMake(17.33, 20.04), controlPoint1: CGPointMake(18.54, 22.74), controlPoint2: CGPointMake(17.33, 21.53))
        bezierPath.addCurveToPoint(CGPointMake(20.04, 17.33), controlPoint1: CGPointMake(17.33, 18.54), controlPoint2: CGPointMake(18.54, 17.33))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(22.74, 20.04))
        bezierPath.addLineToPoint(CGPointMake(22.74, 33.94))
        bezierPath.addCurveToPoint(CGPointMake(20.04, 36.64), controlPoint1: CGPointMake(22.74, 35.43), controlPoint2: CGPointMake(21.53, 36.64))
        bezierPath.addCurveToPoint(CGPointMake(17.33, 33.94), controlPoint1: CGPointMake(18.54, 36.64), controlPoint2: CGPointMake(17.33, 35.43))
        bezierPath.addLineToPoint(CGPointMake(17.33, 20.04))
        bezierPath.addCurveToPoint(CGPointMake(20.04, 17.33), controlPoint1: CGPointMake(17.33, 18.54), controlPoint2: CGPointMake(18.54, 17.33))
        bezierPath.addCurveToPoint(CGPointMake(22.74, 20.04), controlPoint1: CGPointMake(21.53, 17.33), controlPoint2: CGPointMake(22.74, 18.54))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-22.92, -20.22))
        bezierPath.addLineToPoint(CGPointMake(-22.92, -34.12))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, -36.82), controlPoint1: CGPointMake(-22.92, -35.61), controlPoint2: CGPointMake(-21.71, -36.82))
        bezierPath.addCurveToPoint(CGPointMake(-17.51, -34.12), controlPoint1: CGPointMake(-18.72, -36.82), controlPoint2: CGPointMake(-17.51, -35.61))
        bezierPath.addLineToPoint(CGPointMake(-17.51, -20.22))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, -17.51), controlPoint1: CGPointMake(-17.51, -18.72), controlPoint2: CGPointMake(-18.72, -17.51))
        bezierPath.addCurveToPoint(CGPointMake(-22.92, -20.22), controlPoint1: CGPointMake(-21.71, -17.51), controlPoint2: CGPointMake(-22.92, -18.72))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-20.22, -17.51))
        bezierPath.addLineToPoint(CGPointMake(-34.12, -17.51))
        bezierPath.addCurveToPoint(CGPointMake(-36.82, -20.22), controlPoint1: CGPointMake(-35.61, -17.51), controlPoint2: CGPointMake(-36.82, -18.72))
        bezierPath.addCurveToPoint(CGPointMake(-34.12, -22.92), controlPoint1: CGPointMake(-36.82, -21.71), controlPoint2: CGPointMake(-35.61, -22.92))
        bezierPath.addLineToPoint(CGPointMake(-20.22, -22.92))
        bezierPath.addCurveToPoint(CGPointMake(-17.51, -20.22), controlPoint1: CGPointMake(-18.72, -22.92), controlPoint2: CGPointMake(-17.51, -21.71))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, -17.51), controlPoint1: CGPointMake(-17.51, -18.72), controlPoint2: CGPointMake(-18.72, -17.51))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(35.31, -31.48))
        bezierPath.addLineToPoint(CGPointMake(-31.48, 35.31))
        bezierPath.addCurveToPoint(CGPointMake(-35.31, 35.31), controlPoint1: CGPointMake(-32.54, 36.37), controlPoint2: CGPointMake(-34.25, 36.37))
        bezierPath.addCurveToPoint(CGPointMake(-35.31, 31.48), controlPoint1: CGPointMake(-36.37, 34.25), controlPoint2: CGPointMake(-36.37, 32.54))
        bezierPath.addLineToPoint(CGPointMake(31.48, -35.31))
        bezierPath.addCurveToPoint(CGPointMake(35.31, -35.31), controlPoint1: CGPointMake(32.54, -36.37), controlPoint2: CGPointMake(34.25, -36.37))
        bezierPath.addCurveToPoint(CGPointMake(35.31, -31.48), controlPoint1: CGPointMake(36.37, -34.25), controlPoint2: CGPointMake(36.37, -32.54))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-17.51, 20.04))
        bezierPath.addLineToPoint(CGPointMake(-17.51, 33.94))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, 36.64), controlPoint1: CGPointMake(-17.51, 35.43), controlPoint2: CGPointMake(-18.72, 36.64))
        bezierPath.addCurveToPoint(CGPointMake(-22.92, 33.94), controlPoint1: CGPointMake(-21.71, 36.64), controlPoint2: CGPointMake(-22.92, 35.43))
        bezierPath.addLineToPoint(CGPointMake(-22.92, 20.04))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, 17.33), controlPoint1: CGPointMake(-22.92, 18.54), controlPoint2: CGPointMake(-21.71, 17.33))
        bezierPath.addCurveToPoint(CGPointMake(-17.51, 20.04), controlPoint1: CGPointMake(-18.72, 17.33), controlPoint2: CGPointMake(-17.51, 18.54))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-20.22, 22.74))
        bezierPath.addLineToPoint(CGPointMake(-34.12, 22.74))
        bezierPath.addCurveToPoint(CGPointMake(-36.82, 20.04), controlPoint1: CGPointMake(-35.61, 22.74), controlPoint2: CGPointMake(-36.82, 21.53))
        bezierPath.addCurveToPoint(CGPointMake(-34.12, 17.33), controlPoint1: CGPointMake(-36.82, 18.54), controlPoint2: CGPointMake(-35.61, 17.33))
        bezierPath.addLineToPoint(CGPointMake(-20.22, 17.33))
        bezierPath.addCurveToPoint(CGPointMake(-17.51, 20.04), controlPoint1: CGPointMake(-18.72, 17.33), controlPoint2: CGPointMake(-17.51, 18.54))
        bezierPath.addCurveToPoint(CGPointMake(-20.22, 22.74), controlPoint1: CGPointMake(-17.51, 21.53), controlPoint2: CGPointMake(-18.72, 22.74))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(20.04, -22.92))
        bezierPath.addLineToPoint(CGPointMake(33.94, -22.92))
        bezierPath.addCurveToPoint(CGPointMake(36.64, -20.22), controlPoint1: CGPointMake(35.43, -22.92), controlPoint2: CGPointMake(36.64, -21.71))
        bezierPath.addCurveToPoint(CGPointMake(33.94, -17.51), controlPoint1: CGPointMake(36.64, -18.72), controlPoint2: CGPointMake(35.43, -17.51))
        bezierPath.addLineToPoint(CGPointMake(20.04, -17.51))
        bezierPath.addCurveToPoint(CGPointMake(17.33, -20.22), controlPoint1: CGPointMake(18.54, -17.51), controlPoint2: CGPointMake(17.33, -18.72))
        bezierPath.addCurveToPoint(CGPointMake(20.04, -22.92), controlPoint1: CGPointMake(17.33, -21.71), controlPoint2: CGPointMake(18.54, -22.92))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(17.33, -20.22))
        bezierPath.addLineToPoint(CGPointMake(17.33, -34.12))
        bezierPath.addCurveToPoint(CGPointMake(20.04, -36.82), controlPoint1: CGPointMake(17.33, -35.61), controlPoint2: CGPointMake(18.54, -36.82))
        bezierPath.addCurveToPoint(CGPointMake(22.74, -34.12), controlPoint1: CGPointMake(21.53, -36.82), controlPoint2: CGPointMake(22.74, -35.61))
        bezierPath.addLineToPoint(CGPointMake(22.74, -20.22))
        bezierPath.addCurveToPoint(CGPointMake(20.04, -17.51), controlPoint1: CGPointMake(22.74, -18.72), controlPoint2: CGPointMake(21.53, -17.51))
        bezierPath.addCurveToPoint(CGPointMake(17.33, -20.22), controlPoint1: CGPointMake(18.54, -17.51), controlPoint2: CGPointMake(17.33, -18.72))
        bezierPath.closePath()
        VaavudStyle.vaavudDarkGrey.setFill()
        bezierPath.fill()

        CGContextRestoreGState(context)
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
