//
//  Terms.m
//  Vaavud
//
//  Created by Thomas Stilling Ambus on 15/07/2013.
//  Copyright (c) 2013 Andreas Okholm. All rights reserved.
//

#import "Terms.h"

@implementation Terms

+ (NSString*)getTermsOfService {
    
    NSString* html = @"<h3>TERMS AND CONDITIONS OF USE OF THE SERVICES</h3>"
    "<h3>HIGHLIGHTS OF THE TERMS</h3>"
    "<ul>"
    "<li>Endomondo offers services that help you to make your sport experience more fun; however:</li>"
    "<li>When using our Services you are still responsible for any risks associated with your athletic or recreational activities</li>"
    "<li>Endomondo makes no warranties and is not liable for your use of the Services</li>"
    "<li>Always put personal safety first, follow applicable traffic regulations and do not operate your mobile device when in motion or in potential unsafe areas</li>"
    "<li>We take care of the personal information you upload and share per default on the Endomondo community. Please see our privacy policy</li>"
    "<li>We may terminate your accounts if the terms are violated</li>"
    "<li>The service is not intended for children under 13</li>"
    "<li>Contact our support team for help or questions</li>"
    "</ul>"
    "<p>PLEASE READ THE FULL TERMS CAREFULLY BEFORE USING THE ENDOMONDO SERVICES AS THEY ARE A LEGAL DOCUMENT WHICH GOVERNS YOUR RIGHTS AND RESPONSIBILITIES.</p>"
    "<p>BY USING THE SERVICES, YOU AGREE TO TERMS AND ALL REVISIONS THEREOF. IF YOU DO NOT AGREE - DO NOT USE THE SERVICES</p>"
    
    "<p>These terms and conditions (&quot;Terms&quot;), including terms set forth in the privacy policy (&quot;Privacy Policy&quot;), apply for the use of all services (&quot;Services&quot;) rendered by Endomondo, its subsidiaries and affiliates via the website www.endomondo.com (&quot;Site&quot;), all associated sites, distribution channels and via the necessary software applications (&quot;Software&quot;) used in connection with the Services to the Users (&quot;User&quot; or &quot;you&quot;) of the Services. These Terms may be revised from time to time. At any time, the then-current version of the Terms can be found on the Site (www.endomondo.com/terms).</p>"
    
    "<p>Effective October 4, 2012.</p>"
    
    "<h3>1. THE ENDOMONDO SERVICES</h3>"
    "<p>Endomondo ApS is a limited company, incorporated under Danish law with the Danish Commerce and Companies Agency, company registration number (cvr.no) 31 05 57 76, having its registered address at Kanonbaadsvej 12 B, DK-1437 Copenhagen K, Denmark (&quot;Endomondo&quot; or &quot;we&quot;).</p>"
    "<p>Endomondo offers Services that help you to make your sport experience more fun. Services are rendered to and accessed by you via the internet or other data transmission facilities or carriers by use of an applicable device (pc, mobile phone etc.) (&quot;Devise&quot;) of your own choice. Your carrier's normal rates and fees apply.</p>"
    "<p>Age Restrictions. The Services are intended solely for Users who are thirteen (13) years of age or older and it is a violation of the Terms for anyone under 13 to register for the Platform. Thus, you represent and warrant that you are 13 or older. If you are 13 or older, but under the age of 18, you must review the Terns with you parent(s) or legal guardian(s) to ensure that both you and your parent(s) or legal guardian(s) understand and consent to the Terms. A parent or legal guardian accepting the Terms for the benefit of a child, agrees and accepts full responsibility for his or her child's use of the Services, including all financial charges and legal liability that such child may incur.</p>"
    
    "<h3>2. PRIVACY POLICY</h3>"
    "<p>Endomondo's Privacy Policy (www.endomondo.com/privacy) is by reference an incorporated part of these Terms.</p>"
    
    "<h3>3. DISLAIMER OF WARRANTIES AND LIABILITY</h3>"
    "<p>All Services provided &quot;AS IS&quot;: The Services are provided &quot;AS IS&quot; without any express or implied warranties of any kind. Endomondo disclaims all warranties to the fullest extent permitted by law, whether express or implied, including, but not limited to, warranties of title, merchantability, fitness for a particular purpose and non-infringement. Endomondo cannot guarantee that use of the Services will be timely, uninterrupted, secure or error-free, that any defects, errors or malfunctions will be corrected, that the Services or that this Platform or the server that makes the Platform available are free of viruses or anything else harmful. To the fullest extent permitted by law, Endomondo undertakes no warranties or representations as to the use of the Services in terms of correctness, accuracy, adequacy, usefulness, reliability, availability or otherwise. Endomondo is not liable for any communications between Endomondo and you. You bear the responsibility and cost of your choice of data transmission facilities. However, your carrier's normal rates and fees apply.</p>"
    "<p>Personal Safety Notice</p>"
    "<p>You understand and agree that all your athletic and / or recreational activities using the Services may have inherent, implicit and / or expressed risks of bodily injury or death and / or property damage.</p>"
    "<p>You understand and agree that you voluntary and at your own free will assume all known and unknown risks associated with such athletic or recreational activities even if such risks may be claimed to be caused in whole or part by actions, inactions or negligence of Endomondo or others.</p>"
    "<p>You understand and agree that Endomondo will not carry out and is not responsible for any physical inspection, supervision, preparation, execution or conduct of any activities related to the Services, including but not limited to featured, official or User created challenges, routes, friendly competitions or similar, any single or group training activities or any event that utilizes Endomondo's Services; Irrespective of any information or Content related to the Services, Endomondo encourages you to always put safety first, follow applicable traffic regulations, do not change settings on your Device and / or the Software while in motion or in unsafe areas and always be due diligent when exercising.</p>"
    "<p>You understand and agree that you download or otherwise obtain the Services at your own risk, and will be solely responsible for your use and any damage to your mobile Device, computer system or other device by which you access the Services, loss of data or other harm of any kind that may occur as a result thereof.</p>"
    "<p>No Medical advice on physical activity. Endomondo's Services may include features that promote physical activity. However, you understand and agree that Endomondo do not provide medical advice through the Services. You need to consider the risks involved and may need to consult with your medical professional before engaging in any physical activity. Endomondo is not responsible or liable for any injuries or damages you may sustain that result from your use of, or inability to use, the Services, delay or negligence in seeking medical advice from your medical professional.</p>"
    "<p>Amateur athlete eligibility. Endomondo assumes no responsibility or liability for your use of the Services resulting in your ineligibility as an amateur athlete. Check with your amateur athletic association for the rules that apply to you.</p>"
    "<p>Limitation of liability</p>"
    "<p>To the fullest extent permitted by law, Endomondo, its subsidiaries, affiliates, officers, agents, representatives, employees, partners and licensors (&quot;Released Parties&quot;) shall not be liable for any direct, special, incidental, indirect or consequential damages, including but not limited to any lost profits, business interruptions or lost data, that result from the use of, or the inability to use, the Services, including any User Generated Content, even if Endomondo has been advised of the possibility of such damages. That said if Endomondo is found to be liable to you for any damage or loss which is in any way connected with your use of the Services or any content, Endomondo's liability shall not exceed the subscription fees paid by you for the Use of the Services or DKK 1.000 whichever is the higher. You expressly agree and promise not to sue the released parties for any claims, actions, injuries, damages, or losses associated with your use of the Services.</p>"
    "<p>Applicable law may not allow the limitation or exclusion of liability or incidental or consequential damages, so the above limitation or exclusion may not apply to you in its entirety. However, you agree the provisions of liability will be limited to the extent permitted by law.</p>"
    "<p>If links are established to a third-party website, Endomondo is not liable for the contents of such third-party websites. This includes links to partner's website that may use Endomondo's logos as part of a co-branding agreement.</p>"
    "<p>Indemnity</p>"
    "<p>You agree to indemnify, defend, and hold harmless the Released Parties from and against all claims, losses, liabilities, expenses, damages and costs, including, without limitation, attorneys' fees, arising from or relating in any way to your User Generated Content, your use of the Services and / or Content and your conduct in connection with the Services or with other Users of the Services, or any violation of these Terms, any law or the rights of any third party.</p>"
    
    "<h3>4. INTELLECTUAL PROPERTY RIGHTS - USE RESTRICTIONS</h3>"
    "<p>All Intellectual Property to Content as defined below (except from User Generated Content) featured or displayed on the Site or via the Services, is the property of Endomondo, its subsidiaries or Endomondo's business partners and are protected under Danish and other copyright laws, patent and trademark laws and other legislation. &quot;Content&quot; includes but is not limited to logos, trademarks, design, structure, text, graphics, photographs, images, videos, audio, sound, illustrations, interfaces, Software data etc. incorporated into, accompanying or generated by the Software. Endomondo, its subsidiaries and its respective partner's reserves all rights to Content not expressly granted under these Terms. The Endomondo name, the Endomondo logo and avatar and other Endomondo logos and product and names related to the Services are the exclusive trademarks of, and are owned by, Endomondo and may not be used or displayed in any manner without the prior written permission from Endomondo.</p>"
    "<p>If you download Software, including any other Content, from the Site, associated sites and/or distribution channels, the Software is licensed to you by Endomondo. Endomondo does not transfer title to the Software to you. THE LICENSE TO USE THE SOFTWARE AND SERVICES IS LIMITED, PERSONALLY, NON-EXCLUSIVE, NON-TRANSFERABLE AND FOR NON-COMMERCIAL USE ONLY.</p>"
    "<p>NO COMMERCIAL USE. ANY COMMERCIAL USE (E.G. ADVERTISING, SOLICITATION AND OTHER COMMERCIAL CONTENT) IS SUBJECT TO PRIOR WRITTEN AGREEMENT WITH ENDOMONDO. However, Endomondo accepts that non-profit public sports clubs may in connection with non-commercial, public sport events use the Services; provided full reference is made to Endomondo and/or its business partners.</p>"
    "<p>You may not decompile, reverse engineer, disassemble or otherwise attempt to discover any source code, remove, redistribute, sell, assign, transfer any right in, loan, lease, grant any security interest in or any right to the Site, Services, Software, Content, User Generated Content of other Users or any parts thereof. You agree not to use any data mining, robots, scraping or similar data gathering methods. A breach hereof may result in civil and criminal sanctions.</p>"
    
    "<h3>5. USER CONDUCT AND USER GENERATED CONTENT</h3>"
    "<p>To use all the Services available, you must create an Endomondo account either by direct sign up via the Site or by usage of another sign up feature made available by Endomondo via the Services. Any signup is subject to you providing the true, accurate and complete personal information (&quot;User Data&quot;) as prompted by the relevant sign up feature. You undertaker to keep your User Data accurate and current and thus without undue delay update your User Data when relevant.</p>"
    "<p>You are responsible for any actions that take place while using your Endomondo account. Keep your username and password secure and do not allow anyone else to use them to access the Services. Endomondo is not responsible for any loss that results from unauthorized use of your username and password, with or without your knowledge.</p>"
    "<p>Any content that you and other Users post or otherwise make available on or through the Services, except such Content owned by Endomondo, its subsidiaries business partners, shall be deemed &quot;User Generated Content&quot;, including communications (comments, pep talks etc.), materials, information, data, profiles, messages, notes, links to websites, text information, photos, music, videos, designs, graphics, sounds, and any other content.</p>"
    "<p>All User Generated Content submitted by you on the Site or via the Services will be considered non-confidential and non-exclusive. you grant to Endomondo a non-exclusive, non-revocable, worldwide, transferable, royalty-free, perpetual right to use your User Generated Content in any manner or media now or later developed, for any purpose, commercial, advertising, or otherwise, including the right to translate, display, reproduce, modify, create derivative works, sublicense, distribute, assign and commercialize without any payment due to you. Provided, however, that such use shall be conducted with due respect to your privacy as described in the Privacy Policy.</p>"
    "<p>You are granted a limited, non-exclusive right to create a text hyperlink to the Site, provided such link does not portray Endomondo, its trademarks or any of its marks, products or services in a false, misleading, derogatory or otherwise defamatory manner, and provided further that the linking site does not contain any pornographic, illegal, offensive, harassing or otherwise objectionable material.</p>"
    "<p>You agree not to use the Services to post or transmit any material which is or may be infringing on intellectual property rights of others, harassing, threatening, false, misleading, inflammatory, libelous, an invasion of privacy or disclosure of private information, obscene, pornographic, abusive, discriminating, illegal or any material that could constitute or encourage conduct that would be considered a criminal offence, violate the rights of any party or in other ways may give rise to civil liability or non-compliance with any relevant laws of your local jurisdiction.</p>"
    "<p>User Interaction Disclaimer. You are solely responsible for your interactions with other Users, whether online or in person, including but not limited to comments, challenges, routes, pep talks, friendly competition etc. Endomondo assumes no responsibility or liability for any loss or damage resulting from any interaction with other Users of the Services, persons you meet through the Services, or persons who find you because of User Generated Content posted on, by or through the Services. You agree to take reasonable precautions in all interactions with other Users on the Platform, and conduct any necessary investigation before meeting another person. Endomondo is under no obligation to become involved in any disputes between Users, but may do so at its own discretion. If Endomondo chooses to monitor any User Generated Content, it assumes no responsibility for, or any obligation to monitor or remove, such User Generated Content.</p>"
    "<p>Endomondo do not monitor or prescreen User Generated Content prior to posting. Endomondo do not undertake any obligation or liability relating to any User Generated Content or activities of Users on the Services.</p>"
    "<p>Endomondo reserves all rights to edit, remove, or refuse to post any User Data, User Generated Content or terminate your account for any reason.</p>"
    "<p>You acknowledge, consent and agree that Endomondo may access, preserve and disclose your User Data, and other of your User Generated Content if required to do so by law or in a good faith belief that such access preservation or disclosure is reasonably necessary to comply with a legal process, enforce the Terms, respond to claims that any Content or User Generated Content violates the rights of third parties or protect the rights, property or personal safety of Endomondo, its Users and the public.</p>"
    
    "<h3>6. ENDOMONDO WEBSHOP</h3>"
    "<p>Endomondo offers a variety of services and products to its Users. All offers shall be regarded as an invitation to you to make an offer (order) in accordance with the price and terms contained in the offer. However, all orders placed through the Services are subject to Endomondo's acceptance and the then-current applicable terms and conditions of Endomondo's web shop. This means that Endomondo may choose to refuse to accept or may cancel any order, not finally confirmed for delivery by Endomondo, for any or no reason, and without liability to you or anyone else.</p>"
    "<p>THIRD PARTY SERVICE PROVIDERS AND ADVERTISERS</p>"
    "<p>Endomondo may choose at any time to have its business partners' and other third parties' products, services, advertisements and other offers made available via the Services. Any such offerings made available to you are made and offered directly by the applicable third party service provider or advertiser, unless otherwise expressly noted. You acknowledge and accept that if you buy any such products or services offered you are contracting directly with the applicable business partner or third party service provider or advertiser. Your correspondence or business dealings with, or participation in promotions of, third party service providers or advertisers found on or through the Site, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such third party service provider or advertiser. Endomondo shall not be responsible or liable for the performance or nonperformance of any third party service provider or advertiser and any loss or damages of any kind resulting thereof.</p>"
    
    "<h3>7. LINKS</h3>"
    "<p>Endomondo, Users in User Generated Content, third party service providers and advertisers may provide links to other Internet sites and / or other resources. Since Endomondo has no control over such sites and resources, you acknowledge and agree that Endomondo shall not be responsible nor liable for the availability, content, advertising, products, services or other materials on or available from such sites or resources. When we do link to a third-party website, this does not automatically imply that Endomondo endorses that website, its contents or products. Please note that these third-party websites may have their own privacy policy.</p>"
    
    "<h3>8. TERMINATION</h3>"
    "<p>Endomondo reserves the right to change, discontinue and / or terminate any and all Services at any time without notice.</p>"
    "<p>Endomondo may at any time, at its own discretion for any or no reason, and without any warning or notice, edit or remove in whole or in part any Users account and User Generated Content and further to restrict Users use of all or any part of the Services. Endomondo also reserves the right to block Users from certain IP addresses or Device numbers and prevent access to the Services. You understand and agree that some of your User Generated Content, which is displayed outside your profile, in activity feeds, in other parts of the Services, or on other platforms (e.g., Facebook, Twitter etc.), may continue to appear on the Services or on other platforms even after your User Generated Content is removed or your account is terminated.</p>"
    
    "<h3>9. ENDOMONDO PREMIUM</h3>"
    "<p>The Endomondo Premium is a set of premium services provided to the Users (formerly known as Athletes Lounge).</p>"
    "<p>Sign-up. By signing up to Endomondo Premium, you agree to the Terms, including the supplementary terms and conditions in this Chapter (Endomondo Premium). Furthermore your sign up and continuous subscription is contingent on you providing Endomondo adequate and correct payment information and pay due subscription fees and any other incurred charges.</p>"
    "<p>Waiver of right of withdrawal. In order for Endomondo to ensure your immediate access to all the services of Premium, you agree and accept that by ordering Premium, you waive your right to a 14 days right of withdrawal.</p>"
    "<p>Monthly Subscription. Your subscription will continue until you terminate it and is subject to a prepaid monthly subscription fee. The subscription is terminable at any time effective at the end of a calendar month.</p>"
    "<p>Yearly Subscription. Your subscription will continue until you terminate it and is subject to a prepaid yearly subscription fee. You will be notified by email prior to the next yearly payment.</p>"
    "<p>Payment for Endomondo Premium. All fees are paid in advance in accordance with the subscription of your choice, and are drawn from the payment option you submit to Endomondo upon sign up. Payments will continue to be made until you terminate your account.</p>"
    "<p>Payment will be made by a valid credit card accepted by Endomondo. Hence, you authorize us to charge your chosen payment option for your subscription fee until your terminate your account. Should your payment option fail, we will make reasonable efforts to resolve the issue, and notify you of the failure. However, if the issue is not resolved, we will disable your Premium subscription until payment is received. All amounts paid for the Endomondo Premium service, including prepayments, are non-refundable.</p>"
    "<p>The renewal subscription fees will be the same as the initial fee unless you are otherwise notified in advance. Endomondo reserves the right to increase subscription fees or to institute new fees at any time upon reasonable notice posted in advance on this Site. Users who subscribe to Endomondo Premium prior to February 1st, 2013 will not experience an increase in the subscription fee the first three years of their subscription period, as long as they are continuous subscribers throughout the entire period. If they cancel their subscription and choose to subscribe again later on, they will be considered as new subscribers.</p>"
    "<p>Termination notice. Termination is done via your personal 'Settings' page on the Site by choosing &quot;Cancel subscription&quot; under the 'Subscription' menu. You may terminate your subscription to Endomondo Premium at any time effective at the end of a calendar month. Once you have made your cancellation, and received a confirmation, no further charges will be made.</p>"
    "<p>IT IS YOUR RESPONSIBILITY TO TERMINATE YOUR SUBSCRIBTION IN DUE TIME, SHOULD YOU NO LONGER WISH TO SUBSCRIBE. THIS APPLIES IRRESPECTIVE OF YOUR USE OF THE SERVICES.</p>"
    "<p>Refunds. No refunds are made upon termination.</p>"
    
    "<h3>10. SEVERABILITY AND PERSEVERANCE</h3>"
    "<p>Should any provision of the Terms be held invalid, unlawful, void or unenforceable, the remainder of the Terms shall continue to be valid and enforceable. Some jurisdictions do not permit limitations or exclusions on warranties, so the above limitations may not apply to you.</p>"
    "<p>Any provisions of the Terms which by their nature shall survive any termination of use of the Services, irrespective of the cause, including but not restricted to Privacy Policy, Disclaimer of Warranties and Liability, Intellectual Property Rights, Miscellaneous, Severability and Perseverance, Miscellaneous and Applicable law shall survive any termination.</p>"
    
    "<h3>11. MISCELLANEOUS</h3>"
    "<p>Endomondo only may assign its rights and obligations under these Terms to any party at any time without notice to you.</p>"
    "<p>Endomondo may use subcontractors to perform the Services. Such subcontracting parties shall comply with the applicable provisions of the Terms.</p>"
    "<p>The use of the Services shall not construe any joint venture, partnership, employment or agency relationship exists between you and Endomondo.</p>"
    "<p>Endomondo is entitled to revise these Terms at any time. Endomondo will inform you hereof by mail, on the Site, via the Services and / or by other means deemed appropriate and adequate by Endomondo.</p>"
    "<p>Endomondo's failure to insist upon or enforce strict performance of any of these Terms shall not be considered a waiver of any provision or right.</p>"
    "<p>Neither the course of conduct between the parties nor trade practice shall modify any of these Terms.</p>"
    
    "<h3>12. APPLICABLE LAW</h3>"
    "<p>Services are rendered to you under and in accordance with Danish law. Any dispute between you and Endomondo is governed in all respects by Danish law, without regard to its choice of law provisions, and not by the 1980 U.N. Convention on contracts for the international sale of goods (CISG).</p>"
    "<p>You agree that any notice, agreement or other disclosed communication that Endomondo sends you electronically will satisfy any legal communication requirements, including that such communications be in writing.</p>"
    
    "<h3>13. CONTACT AND NOTICES</h3>"
    "<p>All notifications, questions and comments to Endomondo relating to these Terms can be submitted via e-mail to support@endomondo.com.</p>"
    ;
    
    return html;
}

@end
